---
title: "dropping_rec"
author: "Claire Meuter, Mia Guarnieri, Sam Rozal, Chase Tarr"
date: "10/31/2022"
output: html_document
---

##Setup and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach packages
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)
library(rmapshaper)

#mia, chase, and claire's file path

gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```

## dropping rec for climate (error but keeping work in case we want it later)

#Run the model with all covariates

#read in the data
```{r}
#read in the data
rec_model_data <- read_csv(here("/Users/clairemeuter/Library/CloudStorage/GoogleDrive-clairemeuter@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data/AnalysisData/model_df_climate/12_9_2022/climate_model_data_allyears.csv"))
```

#run the rspf
```{r}
#run the rspf

rec_model_allyears <- rspf(conflict ~ dem + aspect + TRI + popdens + lc + road_dens + road_dist + streams_dist + urban_dist + forest_dist + forest_dens + dist_fire_1yr + dist_fire_23yrs + dist_fire_45yrs + drought, family = "binomial", m = 0, B = 1000, data = rec_model_data)

#save the model 
save(rec_model_allyears, file = here("models", "rec_model_allyears.rds"))

#save(rec_model_allyears, file = here(gdrive_data, "/AnalysisData/models_robustness/12_19_21/rec_model_allyears.rds"))


AIC(rec_model_allyears)

```
#running the rec model with climate model 3
```{r}
#run the rspf

rec_model_climate3 <- rspf(conflict ~ dem + lc + forest_dist + popdens  + streams_dist + TRI + urban_dist + dist_fire_1yr + dist_fire_23yrs + dist_fire_45yrs + drought, family = "binomial", m = 0, B = 1000, data = rec_model_data)

#save the model 
save(rec_model_climate3, file = here("models", "rec_model_climate3.rds"))

AIC(rec_model_climate3)
```


#dropping rec for base model and 5 alt models 
```{r}
#read in basemodel dataframe 
rec_model_data_nc <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/model_data_allyears.csv"))

```
#run the models
```{r}
basemodel_allyears_no_rec <- rspf(ID ~ dem + aspect + TRI + popdens + lc + road_dens + road_dist + streams_dist + urban_dist  + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = rec_model_data_nc)

AIC(basemodel_allyears_no_rec)
```
Save the model 
```{r}

#save the model

save(basemodel_allyears_no_rec, file = here("models", "robustness_checks", "basemodel_allyears_no_rec.rds"))

```

#run and save 5 alt models 
```{r}
#Model 1: elevation + land cover + distance to forests + population density + road density + distance to urban areas
mod1_no_rec <- rspf(ID ~ dem + lc + forest_dist + popdens  + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = rec_model_data_nc)

#save model 
save(mod1_no_rec, file = here("models", "robustness_checks", "mod1_no_rec.rds"))

#Model 2: elevation + forest density + land cover + distance to forests + population density  + road density + distance to urban areas

mod2_no_rec <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens  + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = rec_model_data_nc)


#save model 
save(mod2_no_rec, file = here("models", "robustness_checks", "mod2_no_rec.rds"))


#Model 3: elevation + land cover + distance to forests + population density  + distance to streams + terrain ruggedness + distance to urban areas

mod3_no_rec <- rspf(ID ~ dem + lc + forest_dist + popdens  + streams_dist + TRI + urban_dist, family = "binomial", m = 0, B = 1000, data = rec_model_data_nc)

#save model
save(mod3_no_rec, file = here("models", "robustness_checks", "mod3_no_rec.rds"))


#Model 4: elevation + forest density + land cover + distance to forests + population density  + distance to streams + distance to urban areas

mod4_no_rec <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens + streams_dist + urban_dist, family = "binomial", m = 0, B = 1000, data = rec_model_data_nc)

#save model 
save(mod4_no_rec, file = here("models", "robustness_checks", "mod4_no_rec.rds"))


#excluding model 5 bc taking out rec areas doesn't change anything 


```
#check the AIC 
```{r}
AIC(mod4_no_rec)
```

