---
title: "Climate Data Wrangling"
author: "Mia Guarnieri"
date: '2022-11-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
#note - Loading all of the ones Jason used, I don't think we will need all of them 

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(beepr)
library(rgeos)
library(rmapshaper)
#library(rgdal) fyi rgdal has project function as well and will mess up terra project function

#mia and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

#chase's file path
```


```{r}
# CA Raster example 
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#check the coordinate reference system 
crs(ca_raster)


#plot CA raster to confirm
tm_shape(ca_raster) +
  tm_raster() +
  tmap_mode("view")
```

# Fire 

```{r}
#read in fire layers 
ca_fire_2016 <- rast(here(gdrive_data, "/InputData/InputData_Files/fire_intensity_CA_mtbs/2016_fire_intensity_CA_mtbs/mtbs_CA_2016.tif"))

ca_fire_2017 <- rast(here(gdrive_data, "/InputData/InputData_Files/fire_intensity_CA_mtbs/2017_fire_intensity_CA_mtbs/mtbs_CA_2017.tif"))

ca_fire_2018 <- rast(here(gdrive_data, "/InputData/InputData_Files/fire_intensity_CA_mtbs/2018_fire_intensity_CA_mtbs/mtbs_CA_2018.tif"))

ca_fire_2019 <- rast(here(gdrive_data, "/InputData/InputData_Files/fire_intensity_CA_mtbs/2019_fire_intensity_CA_mtbs/mtbs_CA_2019.tif"))

ca_fire_2020 <- rast(here(gdrive_data, "/InputData/InputData_Files/fire_intensity_CA_mtbs/2020_fire_intensity_CA_mtbs/mtbs_CA_2020.tif"))
```


#Getting layers in correct extent, resolution and projection

```{r}
#reproject to the same crs (NAD 83, CA Albers (2011))


ca_fire_2016_albers <- terra::project(ca_fire_2016, ca_raster)

ca_fire_2017_albers <- terra::project(ca_fire_2017, ca_raster)

ca_fire_2018_albers <- terra::project(ca_fire_2018, ca_raster)

ca_fire_2019_albers <- terra::project(ca_fire_2019, ca_raster)

ca_fire_2020_albers <- terra::project(ca_fire_2020, ca_raster)

```

```{r}
#cropping to spatial extent of CA raster

fire_2016_mask <- mask(ca_fire_2016_albers, ca_raster)

fire_2017_mask <- mask(ca_fire_2017_albers, ca_raster)

fire_2018_mask <- mask(ca_fire_2018_albers, ca_raster)

fire_2019_mask <- mask(ca_fire_2019_albers, ca_raster)

fire_2020_mask <- mask(ca_fire_2020_albers, ca_raster)
```

#Save reclassified, reprojected, and clipped rasters to the data drive

**ONLY RUN THIS ONE TIME; IT WILL NOT RUN ONCE THE FILES ARE SAVED**

```{r}
saverast <- function(x){
  
  name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
  #write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
  writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/fire_intensity", name), filetype = "GTiff", overwrite = TRUE)
  
}

saverast(fire_2016_mask)

saverast(fire_2017_mask)

saverast(fire_2018_mask)

saverast(fire_2019_mask)

saverast(fire_2020_mask)

```

