---
title: "Data Visualization"
author: "Mia Guarnieri"
date: '2022-11-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(terra)
library(tmap)
library(here)
library(sf)
library(ResourceSelection)
library(ggplot2)
library(ggtext)


#mia, chase, and claire's file path

gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```

#Conflict data vis

```{r}
conflict <- read_sf(here(gdrive_data, "/IntermediateData/IntermediateData_Files/conflict_formatted/conflict_points/conflict_points.shp")) %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  filter(year != 2022)


ggplot(conflict) +
  geom_histogram(aes(x = year), stat = "count", fill = "#89a676") +
  theme_minimal() +
  labs(x = "Year",
       y = "Number of Reported Conflicts")

```



#Base Model

```{r}
#read in the model

model <- load(here(gdrive_data, "/AnalysisData/models/11_29_2022/model_allyears_noclimate/basemodel_allyears.rds")) #you have to name the object "model or it will not read in right

#read in the CA raster

ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#read in the environmental variables (as close to 2022 as possible)

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
TRI <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

popdens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/road_density/road_density_ca.tif"))

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

forest_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

forest_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/forest_density/forest_dens_2016_mask.tif"))

stackca_base_rast <- c(dem, aspect, TRI, popdens, lc, road_dens, road_dist, streams_dist, urban_dist, rec_dist, forest_dist, forest_dens)

base_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/11_29_2022/model_data_allyears.csv"))

```

```{r}
#changing names of the raster stack to match our model exactly

names(stackca_base_rast) <- c("dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

#any categorical variables used need to be identified first

#making land cover categories factors
lc_factors <- as.factor(base_model_data$lc)

#turning that into a list

f_lc <- levels(lc)

#naming the list "lc" so it matches the model dataframe

names(f_lc) <- "lc"

map <- predict(object = stackca_base_rast, model = basemodel_allyears, fun = predict, factors = f_lc, na.rm = TRUE, type = "response")

plot(map)

#save the map

#writeRaster(map, filename = here(gdrive_data, "/AnalysisData/model_outputs/allyear_base_map.tif"), filetype = "GTiff", overwrite= TRUE)

```

```{r}
#high probability only

top_con <- map

top_con[top_con < 0.7] <- 0

top_con[top_con >= 0.7] <- top_con

plot(top_con)

```




#Data vis with squared climate model

##Climate model all variables
```{r}
#read in the model

model<- load(here("models", "robustness_checks", "squares", "sq_model_climate_all.rds")) #you have to name the object "model or it will not read in right

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
TRI <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

popdens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/road_density/road_density_ca.tif"))

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

forest_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

forest_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/forest_density/forest_dens_2016_mask.tif"))


#fire layers

dist_fire_1yr <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire20_ca_distance.tif"))

dist_fire_23yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire18_19_ca_distance.tif"))

dist_fire_45yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire16_17_ca_distance.tif"))

#drought current - historical

drought <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2021/d2021_masked.tif"))


stackca_clim_rast <- c(dem, aspect, TRI, popdens, lc, road_dens, road_dist, streams_dist, urban_dist, rec_dist, forest_dist, forest_dens, dist_fire_1yr, dist_fire_23yrs, dist_fire_45yrs, drought)

climate_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_climate/12_9_2022/climate_model_data_allyears.csv"))
```

```{r}
#changing names of the raster stack to match our model exactly

names(stackca_clim_rast) <- c("dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens", "dist_fire_1yr", "dist_fire_23yrs", "dist_fire_45yrs", "drought")

#any categorical variables used need to be identified first

#making land cover categories factors
lc_factors <- as.factor(climate_model_data$lc)

#turning that into a list
f <- as.list(levels(lc_factors))

f_lc <- levels(lc)

caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

map <- terra::predict(object = stackca_clim_rast, model = sq_model_climate_all, fun = predict, factors = f_lc, na.rm = TRUE, type = "response")

#save the map

writeRaster(map, filename = here(gdrive_data, "/AnalysisData/model_outputs/allyear_clim_map_squared.tif"), filetype = "GTiff", overwrite= TRUE)

plot(map, main="Model Predictions")
```

#mod 3 climate squared

```{r}
#read in the model

model<- load(here("models", "sq_mod3climate.rds")) #you have to name the object "model or it will not read in right

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
TRI <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

popdens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/road_density/road_density_ca.tif"))

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

forest_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

forest_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/forest_density/forest_dens_2016_mask.tif"))


#fire layers

dist_fire_1yr <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire20_ca_distance.tif"))

dist_fire_23yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire18_19_ca_distance.tif"))

dist_fire_45yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_fire/fire16_17_ca_distance.tif"))

#drought current - historical

drought <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2021/mean_drought_21.tif"))


stackca_clim_rast <- c(dem, aspect, TRI, popdens, lc, road_dens, road_dist, streams_dist, urban_dist, rec_dist, forest_dist, forest_dens, dist_fire_1yr, dist_fire_23yrs, dist_fire_45yrs, drought)

climate_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_climate/12_9_2022/climate_model_data_allyears.csv"))
```

```{r}
#changing names of the raster stack to match our model exactly

names(stackca_clim_rast) <- c("dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens", "dist_fire_1yr", "dist_fire_23yrs", "dist_fire_45yrs", "drought")

#any categorical variables used need to be identified first

#making land cover categories factors
lc_factors <- as.factor(climate_model_data$lc)

#turning that into a list
f <- as.list(levels(lc_factors))

f_lc <- levels(lc)

caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

map <- terra::predict(object = stackca_clim_rast, model = sq_mod3climate, fun = predict, factors = f_lc, na.rm = TRUE, type = "response")

#save the map

writeRaster(map, filename = here(gdrive_data, "/AnalysisData/model_outputs/mod3clim_map_squared.tif"), filetype = "GTiff", overwrite= TRUE)

plot(map, main="Model Predictions")
```


#Model table and plot

```{r}
#mini model to test relation btwn coeffs and std error
mod_dat <- read_csv(here("dredge_data", "climate_model_data_allyears.csv")) %>% 
  mutate(forest_alt = forest_dist * 1000)

mini_mod <- rspf(formula = conflict ~ forest_dist, data = mod_dat, m = 0, B = 1000, family = "binomial")

mini_mod_alt <- rspf(formula = conflict ~ forest_alt, data = mod_dat, m = 0, B = 1000, family = "binomial")

```


```{r}
#load in the model

model<- load(here("models", "sq_mod3climate.rds")) #you have to name the object "model or it will not read in right

#create a model summary object
mod_sum <- summary(sq_mod3climate)

#extract the coefficients from the model summary object
coeffs <- mod_sum$coefficients

library(kableExtra)
nice_table <- coeffs %>% 
  kable() %>% 
  kable_classic(full_width = TRUE, html_font = "Times New Roman")

nice_table

save_kable(nice_table, file = here("/Users/mia/Desktop/Black Bear Aware/coeffs_nicetable.jpeg"), zoom = 2.5)

#convert the row names (variables) to a column for plotting
coeffs_tidy <- cbind(rownames(coeffs), data.frame(coeffs, row.names=NULL)) %>% 
  janitor::clean_names() %>% 
  mutate(coeff_trans = exp(estimate),
         ster_trans = exp(std_error),
         prob_change = ifelse(coeff_trans < 1,
                              (1 - coeff_trans)*100,
                              (coeff_trans - 1)*100))

#remove perennial ice and snow to make plot look more reasonable and convert log odds to probability
coeffs_tidy_nosnow <- coeffs_tidy %>% 
  filter(rownames_coeffs != "lcperrenial_ice_snow") %>% 
  mutate(coeff_trans = exp(estimate)) 

#test plot
ggplot(coeffs_tidy_nosnow, aes(x = coeff_trans, y = rownames_coeffs)) + 
  geom_point() +
  geom_pointrange(aes(xmin = estimate-std_error, xmax = estimate+std_error)) +
  scale_x_continuous(breaks = seq(-3, 4, 0.5))

##Making a nicer table

#separate into df by variable type

ice_snow <- coeffs_tidy[10,] %>% 
  mutate(coeff_trans = exp(estimate),
         prob_change = (coeff_trans - 1) * 100,
         ster_min = exp(estimate - (2 * std_error)),
         ster_max = exp(estimate + (2 * std_error)),
         cimax = (1 - ster_min)*100,
         cimin = (1 - ster_max)*100)

elev <- coeffs_tidy_nosnow[c(2), ] %>% 
  mutate(coeff_trans = exp(estimate*1000),
         prob_change = (coeff_trans - 1)*100) %>% 
  mutate(rownames_coeffs = c("Elevation"))

tri <- coeffs_tidy_nosnow[c(18), ] %>% 
  mutate(coeff_trans = exp(estimate),
         prob_change = (1 - coeff_trans)*100) %>% 
  mutate(rownames_coeffs = c("Terrain Ruggedness"))

bluevar_lconly <- coeffs_tidy_nosnow[c(3:12), ] %>% 
  mutate(coeff_trans = exp(estimate),
         prob_change = (coeff_trans - 1) * 100,
         ster_min = exp(estimate - (2 * std_error)),
         ster_max = exp(estimate + (2 * std_error)),
         cimax = (ster_max - 1) * 100,
         cimin = ifelse(ster_min > 1,
                        (ster_min - 1) * 100,
                        (1 - ster_min) * 100)) %>% 
  mutate(rownames_coeffs = c("High-Intensity Development", "Low-Intensity Development", "Medium-Intensity Development", "Developed Open Space", "Forest", "Grassland/Herbaceous", "Open Water", "Planted/Cultivated", "Shrub/Scrub", "Wetlands"))

greenvar <- coeffs_tidy_nosnow[c(13, 17), ] %>% 
  mutate(coeff_trans = exp(estimate*1000),
         prob_change = (1 - coeff_trans)*100) %>% 
  mutate(rownames_coeffs = c("Distance to Forest", "Distance to Streams"))

#setting up the human variables
#separate the distance variables

gray_dist <- coeffs_tidy_nosnow[c(16, 19), ] %>% 
  mutate(coeff_trans = exp(estimate*1000),
         ster_trans = exp(std_error * 1000),
         prob_change = (1 - coeff_trans)*100,
         ster_min = exp((estimate - (2 * std_error))*1000),
         ster_max = exp((estimate + (2 * std_error))*1000),
         cimax = (1 - ster_min)*100,
         cimin = (1 - ster_max)*100) %>% 
  mutate(rownames_coeffs = c( "Distance to Recreational Areas", "Distance to Urban Areas"))

gray_pop <- coeffs_tidy_nosnow[c(14), ] %>% 
  mutate(coeff_trans = exp(estimate),
         ster_trans = exp(std_error),
         prob_change = ifelse(coeff_trans < 1,
                              (1 - coeff_trans)*100,
                              (coeff_trans - 1)*100),
         ster_min = exp(estimate - (2 * std_error)),
         ster_max = exp(estimate + (2 * std_error)),
         cimax = (ster_min - 1)*100,
         cimin = (ster_max - 1)*100) %>% 
  mutate(rownames_coeffs = c("Population Density"))

grayvar<- rbind(gray_dist, gray_pop)

orangevar <- coeffs_tidy_nosnow[c(20:22), ] %>% 
  mutate(coeff_mult = estimate * 1000,
         ster_mult = std_error * 1000,
         coeff_trans = exp(coeff_mult),
         prob_change = (1 - coeff_trans) * 100,
         ster_min = exp((estimate - (2 * std_error))*1000),
         ster_max = exp((estimate + (2 * std_error))*1000),
         cimax = (1 - ster_min)*100,
         cimin = (1 - ster_max)*100) %>% 
  mutate(rownames_coeffs = c("Distance to Fire 1 Year Ago", "Distance to Fire 2-3 Years Ago", "Distance to Fire 4-5 Years Ago"))

brownvar <- coeffs_tidy_nosnow[c(23), ] %>% 
  mutate (coeff_trans = exp(estimate),
         ster_trans = exp(std_error),
         prob_change = (1 - coeff_trans)*100)

intercept <- coeffs_tidy_nosnow[c(1), ] %>% 
  mutate (rownames_coeffs = c("Intercept"))

#nice plot of all variables - OUTDATED, DO NOT USE
ggplot() + 
  geom_point(bluevar_nonlc, mapping = aes(x = coeff_trans, y = rownames_coeffs), color = "#528faa") +
  #geom_pointrange(bluevar, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error), color = "#528faa") +
  geom_point(greenvar, mapping = aes(x = coeff_trans, y = rownames_coeffs), color = "#89a676") +
  #geom_pointrange(greenvar, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error), color = "#89a676") +
  geom_point(grayvar, mapping = aes(x = coeff_trans, y = rownames_coeffs), color = "#c3c2b1") +
 # geom_pointrange(grayvar, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error), color = "#c3c2b1") +
  geom_point(orangevar, mapping = aes(x = coeff_trans, y = rownames_coeffs), color = "#ffbd59") +
  #geom_pointrange(orangevar, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error), color = "#ffbd59") +
  geom_point(brownvar, mapping = aes(x = coeff_trans, y = rownames_coeffs), color = "#b68a67") +
  #geom_pointrange(brownvar, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error), color = "#b68a67") +
  #geom_point(intercept, mapping = aes(x = coeff_trans, y = rownames_coeffs)) +
  #geom_pointrange(intercept, mapping = aes(x = coeff_trans, y = rownames_coeffs, xmin = estimate-std_error, xmax = estimate+std_error)) +
  #scale_x_continuous(breaks = seq(-3, 4, 0.5)) +
  labs(y = "Coefficient", x = "Estimate") +
  theme_minimal() +
  theme(plot.caption = ggtext::element_markdown(hjust = 0),
        text = element_text(family = "Times New Roman"))


#nice plot for climate
ggplot(orangevar, mapping = aes(x = prob_change, y = reorder(rownames_coeffs, prob_change))) + 
  geom_point(color = "#cc5500", size = 3) +
  geom_linerange(aes(xmin = cimin, xmax = cimax), color = "#cc5500") +
  labs(y = "Coefficient", x = "Estimate") +
  theme_minimal() +
  theme(plot.caption = ggtext::element_markdown(hjust = 0),
        text = element_text(family = "Times New Roman")) 

#nice plot for land cover

ggplot(bluevar_lconly, mapping = aes(x = prob_change, y = reorder(rownames_coeffs, prob_change))) + 
  geom_point(color = "#528faa", size = 3) +
  geom_linerange(aes(xmin = cimin, xmax = cimax), color = "#528faa") +
  labs(y = "Coefficient", x = "Estimate") +
  theme_minimal() +
  theme(plot.caption = ggtext::element_markdown(hjust = 0),
        text = element_text(family = "Times New Roman"))

#nice plot for human correlates
ggplot(grayvar, mapping = aes(x = prob_change, y = reorder(rownames_coeffs, prob_change))) + 
  geom_point(color = "#777777", size = 3) +
  geom_linerange(aes(xmin = cimin, xmax = cimax), color = "#777777") +
  labs(y = "Coefficient", x = "Estimate") +
  theme_minimal() +
  theme(plot.caption = ggtext::element_markdown(hjust = 0),
        text = element_text(family = "Times New Roman"))

```

```{r}
library(kableExtra)

coeffs_nicetable <- coeffs_tidy %>%
  kable(escape = FALSE) %>% 
  kable_styling(full_width = FALSE, position = "center") 

coeffs_nicetable

library(magick)

save_kable(coeffs_nicetable, file = here("/Users/mia/Desktop/Black Bear Aware/coeffs_nicetable.jpeg"), zoom = 2.5)
```



#Projection map

```{r}
#read in the model

model<- load(here("models", "sq_mod3climate.rds")) #you have to name the object "model or it will not read in right

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
TRI <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

popdens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/road_density/road_density_ca.tif"))

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

forest_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

forest_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/forest_density/forest_dens_2016_mask.tif"))


#fire layers

dist_fire_1yr <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_proj_fire/dist_proj_fire_2029_ca.tif"))

dist_fire_23yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_proj_fire/dist_proj_fire_2027_2028_ca.tif"))

dist_fire_45yrs <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/dist_proj_fire/dist_proj_fire_2025_2026_ca.tif"))

#drought current - historical

drought <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/drought/pdsi_masked.tif"))


stackca_clim_rast <- c(dem, aspect, TRI, popdens, lc, road_dens, road_dist, streams_dist, urban_dist, rec_dist, forest_dist, forest_dens, dist_fire_1yr, dist_fire_23yrs, dist_fire_45yrs, drought)

climate_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_climate/1_31_2023/climate_model_data_allyears.csv"))
```

```{r}
#changing names of the raster stack to match our model exactly

names(stackca_clim_rast) <- c("dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens", "dist_fire_1yr", "dist_fire_23yrs", "dist_fire_45yrs", "drought")

#any categorical variables used need to be identified first

#making land cover categories factors
lc_factors <- as.factor(climate_model_data$lc)

#turning that into a list
f <- as.list(levels(lc_factors))

f_lc <- levels(lc)

caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

map <- terra::predict(object = stackca_clim_rast, model = sq_mod3climate, fun = predict, factors = f_lc, na.rm = TRUE, type = "response")

#save the map

writeRaster(map, filename = here(gdrive_data, "/AnalysisData/model_outputs/projected_mod3_clim_map_squared.tif"), filetype = "GTiff", overwrite= TRUE)

plot(map, main="Model Predictions")
```

#Differenced map

```{r}

current <- rast(here(gdrive_data, "/AnalysisData/model_outputs/mod3clim_map_squared.tif"))

future <- rast(here(gdrive_data, "/AnalysisData/model_outputs/projected_mod3_clim_map_squared.tif"))

diff <- future - current

plot(diff)

plot(current)

plot(future)

writeRaster(diff, filename = here(gdrive_data, "/AnalysisData/model_outputs/differenced_conflict_risk.tif"), filetype = "GTiff", overwrite= TRUE)
```

#CDFW administrative regions

```{r}
#read in raster for reprojection

ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#read in regions shapefile and reproject
cdfw_regions <- read_sf(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CDFW_Regions/CDFW_Regions_20221031_wm.shp")) %>% 
  st_transform(crs = crs(ca_raster))

#save reprojected shapefile

st_write(cdfw_regions, dsn = here(gdrive_data, "/IntermediateData/IntermediateData_Files/cdfw_regions_reproj/cdfw_regions.shp"))

```

#Marginal effects

```{r}
#attempt to plot the predicted conflec against pop dens - didn't work so well

#marginal effects plot
library(ResourceSelection)

model<- load(here("models", "sq_mod3climate.rds")) #you have to name the object "model or it will not read in right

mep(sq_mod3climate, which = "popdens", col.points = "#c3c2b1", pch = 1, n = 100, family = "Times New Roman")

```

