---
title: "demographic_exploration"
author: "Sam Rozal"
date: "2023-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach packages
library(tidyverse)
library(here)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)
library(rmapshaper)
library(terra)

#mia, chase, and claire's file path

#gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#mia's file path
#gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```

# exploring high conflict points where nonreporting is occurring and understanding the demographics of the areas
```{r}
#loading in data
mod3_rast <- rast(here(gdrive_data, "/AnalysisData/model_outputs/projected_mod3_clim_map_squared.tif"))

ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

county_demographics <- vect(here(gdrive_data, "/IntermediateData/IntermediateData_Files/census_demographics/MSSA_Detail.shp"))

```


```{r}
ca_amind_alone <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_AMIND_ALONE.tif/CAPOP_2020_100m_AMIND_ALONE.tif"))

ca_amind_combo <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_AMIND_COMBO.tif/CAPOP_2020_100m_AMIND_COMBO.tif"))

ca_hisp <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_HISP.tif/CAPOP_2020_100m_HISP.tif"))

ca_minors <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_MINORS.tif/CAPOP_2020_100m_MINORS.tif"))

ca_nhamind <- rast(here(gdrive_data, "/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_NHAMIND.tif/CAPOP_2020_100m_NHAMIND.tif"))

ca_nhasian <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_NHASIAN.tif/CAPOP_2020_100m_NHASIAN.tif"))

ca_nhhipi <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_NHHIPI.tif/CAPOP_2020_100m_NHHIPI.tif"))

ca_nhothermulti <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_NHOTHERMULTI.tif/CAPOP_2020_100m_OTHERMULTI.tif"))

ca_nhwhite <- rast(here(gdrive_data, "/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_NHWHITE.tif/CAPOP_2020_100m_NHWHITE.tif"))

ca_total <- rast(here(gdrive_data,"/InputData/InputData_Files/demographics_data_2020/CAPOP_2020_100m_TOTAL.tif/CAPOP_2020_100m_TOTAL.tif"))

```


```{r}
ca_amind_alone_proj <- project(ca_amind_alone,"epsg:6414")

ca_amind_combo_proj <- project(ca_amind_combo, "epsg:6414")

ca_hisp_proj <- project(ca_hisp, "epsg:6414")

ca_minors_proj <- project(ca_minors, "epsg:6414")

ca_nhamind_proj <- project(ca_minors,"epsg:6414")

ca_nhasain_proj <- project(ca_nhasian,"epsg:6414")

ca_nhhipi_proj <- project(ca_nhhipi,"epsg:6414")

ca_nhothermulti_proj <- project(ca_nhothermulti, "epsg:6414")

ca_nhwhite_proj <- project(ca_nhwhite,"epsg:6414")

ca_total_proj <- project(ca_total, "epsg:6414")


```

```{r}
demographic_stack <- c(ca_amind_alone_proj, ca_amind_combo_proj, ca_hisp_proj, ca_minors_proj, ca_nhamind_proj, ca_nhasain_proj, ca_nhhipi_proj, ca_nhothermulti_proj, ca_nhwhite_proj, ca_total_proj)

```

```{r}
#read in model data 

high_conflict_current <- rast(here(gdrive_data,"/AnalysisData/model_outputs/mod3sq_current_highconf.tif"))

buffered_conflict <- vect(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/conflict_buffered_refined/conflict_buffered_refined.shp"))

```

```{r}
high_conflict_reporting <- mask(high_conflict_current, buffered_conflict)

high_conflict_reporting_proj <- project(high_conflict_reporting,ca_total_proj)
```

```{r}
high_conflict_no_reporting <- mask(high_conflict_current, buffered_conflict, inverse=TRUE)

high_conflict_no_reporting_proj <- project(high_conflict_no_reporting, ca_total_proj)

```

```{r}
demographic_mask_reporting <- mask(demographic_stack, high_conflict_reporting_proj)

demographic_mask_no_reporting <- mask(demographic_stack, high_conflict_no_reporting_proj)
```
```{r}

```



