---
title: "Projection Data"
author: "Chase Tarr"
date: "2023-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
#note - Loading all of the ones Jason used, I don't think we will need all of them 

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(beepr)
library(rgeos)
library(rmapshaper)
library(raster)
library(stars)
library(purrr)
library(remotes)
library(rgdal)
library(sp)
library(raster)

#mia and claire's and Chase's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"
```

```{r}
install_github("Sibada/scPDSI")

```

```{r}
library(scPDSI)
```


# california raster
```{r}
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

```

# Read in drought data

```{r}
CalAdapt_PE <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-5/et_month_HadGEM2-CC_rcp45_2030-01.v0.CA_NV.tif")) %>%
  terra::project(ca_raster)

plot(CalAdapt_PE)

```

```{r}
CalAdapt_P <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-5/rainfall_month_CCSM4_rcp45_2030-01.v0.CA_NV.tif"))%>% terra::project(ca_raster)

plot(CalAdapt_P)
```





#```{r}
.onLoad <- function(libname, pkgname) {
  ops <- options()
  pdsi.ops <- list(
    # Calculating the conventional PDSI
    # Duration factors
    PDSI.p = 0.897,
    PDSI.q = 1/3,

    # Coefficients of climate characteristic
    PDSI.coe.K1.1 = 1.5,
    PDSI.coe.K1.2 = 2.8,
    PDSI.coe.K1.3 = 0.5,

    PDSI.coe.K2 = 17.67
  )

  toset <- !(names(pdsi.ops) %in% names(ops))
  if(any(toset)) {
    options(pdsi.ops[toset])
  }
}
```

#```{r}
options(PDSI.coe.K1.1 = 1.6)
options(PDSI.coe.K1.3 = 0.4)
options(PDSI.coe.K2 = 16.84)
options(PDSI.p = 0.755)
options(PDSI.q = 1/1.63)
gb_pdsi <- pdsi(P, PE, start = 1960, sc = FALSE)
lines(gb_pdsi$X, col = 'red')
```


#```{r}
C_pdsi <- function(P, PE, AWC, s_yr, e_yr, calib_s_yr, calib_e_yr, sc, K1_1, K1_2, K1_3, K2, p, q) {
    .Call('_scPDSI_C_pdsi', PACKAGE = 'scPDSI', P, PE, AWC, s_yr, e_yr, calib_s_yr, calib_e_yr, sc, K1_1, K1_2, K1_3, K2, p, q)
}
```

#```{r}
pdsi <- function(P, PE, AWC = 100, start = NULL, end = NULL, cal_start = NULL, cal_end = NULL,
                 sc = TRUE) {

  freq <- 12

  if(is.null(start)) start <-  1;
  if(is.null(end)) end <- start + ceiling(length(P)/freq) - 1

  if(is.null(cal_start)) cal_start <- start
  if(is.null(cal_end)) cal_end <- end

  res <- C_pdsi(P, PE, AWC, start, end, cal_start, cal_end, sc,
                getOption("PDSI.coe.K1.1"),
                getOption("PDSI.coe.K1.2"),
                getOption("PDSI.coe.K1.3"),
                getOption("PDSI.coe.K2"),
                getOption("PDSI.p"),
                getOption("PDSI.q"))

  names(res) <- c("inter.vars", "clim.coes", "calib.coes")

  inter.vars <- res[[1]]
  clim.coes <- res[[2]]
  calib.coes <- res[[3]]
  inter.vars[inter.vars == -999.] <- NA

  out <- list(call = match.call(expand.dots=FALSE),
              X = stats::ts(inter.vars[, 14], start = start, frequency = freq),
              inter.vars = stats::ts(inter.vars[, 3:13], start = start, frequency = freq))

  colnames(out$inter.vars) <- c("P", "PE", "PR", "PRO", "PL", "d", "Z",
                                "Prob", "X1", "X2", "X3")

  dim(calib.coes) <- c(2, 5)
  colnames(calib.coes) <- c("m", "b", "p", "q", "K2")
  rownames(calib.coes) <- c('wet', 'dry')

  colnames(clim.coes) <- c("alpha", "beta", "gamma", "delta", "K1")
  rownames(clim.coes) <- month.name

  out$clim.coes <- clim.coes
  out$calib.coes <- calib.coes

  class(out) <- "pdsi"
  out
}

```



#```{r}
pdsi(P, PE, AWC = 100, start = NULL, end = NULL, cal_start = NULL, cal_end = NULL,
                 sc = TRUE)
```

#```{r}
av <- available.packages(filters=list())
av[av[, "PACKAGE"] == pkg, ]
```


<<<<<<< HEAD
#example code used online
#```{r}
data(P_PE)

P <- P_PE$P
PE <- P_PE$PE
sc_pdsi_P_PE <- pdsi(P, PE, start = 2006)
#stop here for pdsi (x) values

plot(sc_pdsi) # plot PDSI
plot(sc_pdsi, index = "PHDI") # plot PHDI
plot(sc_pdsi, index = "WPLM") # plot weighted PDSI

# Without self-calibrating.
ori_pdsi <- pdsi(P, PE, start = 2006, sc = FALSE)
plot(ori_pdsi)

# Without self-calibrating and use standards of
# mainland China. (GB/T 20481-2017)
options(PDSI.coe.K1.1 = 1.6)
options(PDSI.coe.K1.3 = 0.4)
options(PDSI.coe.K2 = 16.84)
options(PDSI.p = 0.755)
options(PDSI.q = 1/1.63)
gb_pdsi <- pdsi(P, PE, start = 1960, sc = FALSE)
plot(gb_pdsi)
#```

#```{r}
pdsi_merged <- terra::merge(sc_pdsi_P_PE[[2]], sc_pdsi_P_PE[[3]], sc_pdsi_P_PE[[4]], sc_pdsi_P_PE[[5]])

pdsi_rast <- rast(pdsi_merged)

#reproject
pdsi_calbers <- terra::project(pdsi_rast, ca_raster)

#mask to CA
pdsi_masked <- mask(pdsi_calbers, ca_raster)
#```




#```{r}
library(scPDSI)
data(Lubuge)

 P <- Lubuge$P
 PE <- Lubuge$PE
 lubugesc_pdsi <- pdsi(P, PE, start = 1960)
 plot(lubugesc_pdsi$X)

 # Without self-calibrating.
 ori_pdsi <- pdsi(P, PE, start = 1960, sc = FALSE)
 plot(ori_pdsi$X)

 # Without self-calibrating and use standards of
 # mainland China. (GB/T 20481-2006)
 options(PDSI.coe.K1.1 = 1.6)
 options(PDSI.coe.K1.3 = 0.4)
 options(PDSI.coe.K2 = 16.84)
 options(PDSI.p = 0.755)
 options(PDSI.q = 1/1.63)
 gb_pdsi <- pdsi(P, PE, start = 1960, sc = FALSE)
 lines(gb_pdsi$X, col = 'red')

#```


#```{r}
require(raster)


  

shp.PE <- rasterToPolygons(CalAdapt_P)

#ca_vector <- as.polygons(ca_raster)

PE_calbers <- terra::project(shp.PE, ca_raster)

rec_areas_PEP_mask <- crop(rec_areas_PEP_calbers, ca_raster)

rec_areas_PEP_raster <- rasterize(rec_areas_PEP_mask, ca_raster)

#mask to CA
caladapt_masked <- mask(caladapt_calbers, ca_raster)

r.to.poly<-rasterToPolygons(rs, dissolve = T)

int.r <-raster::intersect(r.to.poly,shp) 

proj4string(shp) <- proj4string(r.to.poly)
#```

trying sams merged files from pdsi exploration
```{r}
caladapt_pe_calbers <- terra::project(CalAdapt_PE, ca_raster)

#mask to CA
caladapt_pe_masked <- mask(caladapt_pe_calbers, ca_raster)

#test plot
#plot(caladapt_pe_masked)
```

```{r}
caladapt_P_calbers <- terra::project(CalAdapt_P, ca_raster)

#mask to CA
caladapt_P_masked <- mask(caladapt_P_calbers, ca_raster)

#test plot
#plot(caladapt_P_masked)
```

```{r}
#merging/stacking the rasters 
caladapt_merged <- c(caladapt_pe_masked,caladapt_P_masked)

#plot(caladapt_merged)

#converting to a dataframe
caladapt_merged_df <- as.data.frame(caladapt_merged, xy=TRUE) %>% 
  rename(P = "rainfall_month_CCSM4_rcp45_2030-01.v0.CA_NV",
    PE = "et_month_HadGEM2-CC_rcp45_2030-01.v0.CA_NV")


P <- caladapt_merged_df$P
PE <- caladapt_merged_df$PE

# trying to figure out how to add PDSI calculation into DF
pdsi_df<-(pdsi(P,PE, start = 2030))

cal_adapt_pdsi_Df <- dplyr::mutate(caladapt_merged_df,
              pdsi_measure = (pdsi_df$X[1:7901930]))

cal_adapt_pdsi_df <- as.matrix(cal_adapt_pdsi_Df)

df <- subset(cal_adapt_pdsi_Df, select = -c(P,PE))

head(cal_adapt_pdsi_Df)

head(df)

#df2 <- subset(df, select = -c(x,y))

#write.table(cal_adapt_pdsi_Df, file = here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/pdsi_df.csv"), row.names = FALSE)

#df_csv_write <- apply(df,2,as.character)

```
#raster package
#```{r}
pdsi_raster <- rasterFromXYZ(df)

plot(pdsi_raster)
#```
#terra package
```{r}
pdsi_rast_2030 <- terra::rast(df)

plot(pdsi_rast_2030)

caladapt_Pdsi_calbers <- terra::project(pdsi_rast_2030, ca_raster)

#mask to CA
caladapt_pdsi_masked <- mask(caladapt_Pdsi_calbers, ca_raster)
```


```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/drought", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(caladapt_pdsi_masked)
```
#no
```{r}
colnames(df) <- c('x','y','vals')

r_obj <- raster(xmn=-180, xmx=180, ymn=-90, ymx=90, resolution=c(230,230))

# use rasterize to create desired raster
r_data <- rasterize(x=df[, 1:2], # lon-lat data
                    y=r_obj, # raster object
                    field=df[, 3], # vals to fill raster with
                    fun=mean)
```

#no
```{r}
coordinates(df2) <- ~ x + y

gridded(df2) <- TRUE

class(df2)

str(df2@data)

m = SpatialPixelsDataFrame(points = df[c("x", "y")], data = df)


r <- raster(m)

r2 <- raster(m[3])

#r2 <- rasterize(x=m,y=r, field="pdsi_measure")

plot(r2)

raster_pd <- raster(cal_adapt_psdi_df, xmn=0, xmx=1, ymn=0, ymx=1, crs="", template=NULL)

rasterDF <- terra::rast(df)
```

#no
```{r}
df_num <- as.numeric(unlist(cal_adapt_pdsi_df))

pdsi_raster <- rasterFromXYZ(cal_adapt_pdsi_df)
```

#no
```{r}
Proj4js.defs= "+proj=utm +zone=18 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

st_crs(Proj4js.defs)

utm18nCRS <- st_crs(Proj4js.defs)

class(utm18nCRS)

plot_locations_pdsi <- st_as_sf(cal_adapt_pdsi_df, coords = c("x", "y"), crs = utm18nCRS)

st_crs(plot_locations_pdsi)


```

#no
```{r}
WGScoor<-  cal_adapt_pdsi_df #data to convert
coordinates(WGScoor)=~x+y #column names of the lat long cols
proj4string(WGScoor) <- CRS("+init=epsg:28992") # set coordinate system to WGS
WGScoor.df <- SpatialPointsDataFrame(WGScoor, data.frame(id=1:length(WGScoor)))
LLcoor<-spTransform(WGScoor.df,CRS("+proj=longlat"))
LLcoor.df=SpatialPointsDataFrame(LLcoor, data.frame(id=1:length(LLcoor)))
pdsi_shp <- writeOGR(LLcoor.df, dsn=getwd(),layer="MyShapefile1",driver="ESRI Shapefile")
```


