---
title: "model_selection"
author: "Claire Meuter"
date: "2022-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)
library(rmapshaper)
library(MuMIn)
#mia, chase, and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"
```

#Read in all year models

```{r}
#base model
load(here("models", "basemodel_allyears.rds"))

#base model data
base_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/11_1_2022/model_data_allyears.csv"))

#climate model

load(here("models", "climate_model_allyears.rds"))

#climate model data

climate_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_climate/11_10_2022/climate_model_data_allyears.csv"))
```


#Attempt a dredge
Note: this has not worked, takes too long to run

```{r}
dredged_model <- dredge(global.model = basemodel_allyears, rank = "AIC")
```

#Set up 5 alternative models, with the same covariates as the Hagani et al models

```{r}
#our model (all covariates)
basemodel_allyears <- rspf(ID ~ dem + aspect + TRI + popdens + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = base_model_data)

#Model 1: elevation + land cover + distance to forests + population density + distance to recreational areas+ road density + distance to urban areas
mod1 <- rspf(ID ~ dem + lc + forest_dist + popdens + rec_dist + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = base_model_data)

#Model 2: elevation + forest density + land cover + distance to forests + population density + distance to recreational areas + road density + distance to urban areas

mod2 <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens + rec_dist + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = base_model_data)

#Model 3: elevation + land cover + distance to forests + population density + distance to recreational areas + distance to streams + terrain ruggedness + distance to urban areas

mod3 <- rspf(ID ~ dem + lc + forest_dist + popdens + rec_dist + streams_dist + TRI + urban_dist, family = "binomial", m = 0, B = 1000, data = base_model_data)

#Model 4: elevation + forest density + land cover + distance to forests + population density + distance to recreational areas + distance to streams + distance to urban areas

mod4 <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens + rec_dist + streams_dist + urban_dist, family = "binomial", m = 0, B = 1000, data = base_model_data)

#Model 5: elevation + land cover + distance to forests + population density + distance to streams + terrain ruggedness + distance to urban areas

mod5 <- rspf(ID ~ dem + lc + forest_dist + popdens + streams_dist + TRI + urban_dist, family = "binomial", m = 0, B = 1000, data = base_model_data)

```

