---
title: "Model Creation"
author: "Mia Guarnieri"
date: '2022-10-19'
output: html_document
---

##Setup and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach packages
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)

#mia, chase, and claire's file path
#gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```

#Load in data layers

##Conflict data

```{r}
#conflict data - read in and merged to one layer
conflict <- read_sf(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/conflict_buffered_refined/conflict_buffered_refined.shp"))

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
ter_rug <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

pop16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2016_mask.tif"))

pop17 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2017_mask.tif"))

pop18 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2018_mask.tif"))

pop19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2019_mask.tif"))

pop20 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2020_mask.tif"))

pop21 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc13_reclassed.tif"))

lc16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc16_reclassed.tif"))

lc19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/road_density_arc/2022_10_26_RoadDensity_ClaireERSI.tif"))

road_dens2 = resample(road_dens, dem)

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist_13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua13_ca_distance.tif"))

urban_dist_16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua16_ca_distance.tif"))

urban_dist_19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

fc_dist_13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc13_ca_distance.tif"))

fc_dist_16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc16_ca_distance.tif"))

fc_dist_19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

fdens <- rast(here(gdrive_data, ""))

```

#Process data by year

##2016

```{r}

#extract values for 2016, select only conflict indicator and geometry, and dissolve polygons

con_16 <- conflict %>% 
  filter(year == 2016) %>% 
  select(conflict, geometry) %>% 
  st_union()

#create a spatvector for processing in terra

con_16_sv <- vect(con_16)

#create a raster stack of all variables

stack16 <- c(dem, aspect, ter_rug, pop16, lc16,road_dens2, road_dist, streams_dist, urban_dist_16, fc_dist_16)
#note - I had to change the extent for road density which is why its road_dens2 

#extract data points from these rasters and add them to the shapefile dataframe

var_ex16 <- extract(stack16, con_16_sv, method = "simple", bind = TRUE, ID = TRUE)

var_df16 <- as.data.frame(var_ex16)

#run it in the model

model16 <- rspf(ID ~ aspect + TRI + category, family = "binomial", m = 0, B = 1000, data = var_df)

```

#Sam is playing around with the code here:
```{r}
#try to stack rasters

raster_stack_test <- c(roads15_ca_distance,stream17_ca_distance)

tm_shape(raster_stack_test) +
  tm_raster() +
  tmap_mode("view")

raster_test_df <- as.data.frame(raster_stack_test)

```

##2017

```{r}

#extract values for 2016

con_17 <- conflict_buffer %>% 
  filter(year == 2017)

#create a spatvector for processing in terra

con_17_sv <- vect(con_17)

#create a raster stack of all variables

stack17 <- c(dem, aspect, ter_rug, pop17, lc16, road_dens2, road_dist, urban_dist_16, fc_dist_16)
#note - I had to change the extent for road density which is why its road_dens2 

#extract data points from these rasters and add them to the shapefile dataframe

var_ex <- extract(stack17, con_17_sv, method = "simple", bind = TRUE, ID = TRUE)

var_df_17 <- as.data.frame(var_ex)

#run it in the model

model <- rspf(ID ~ aspect + TRI + category, family = "binomial", m = 0, B = 1000, data = var_df_17)

```

##2018

##2019

##2020

##2021

