---
title: "pdsi_exploration"
author: "Sam Rozal"
date: "2023-01-29"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(remotes)

#mia's file path
#gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```


```{r}
install_github("Sibada/scPDSI")

library(scPDSI)
```


<<<<<<< HEAD

```{r}
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
```

# Read in drought data

```{r}
CalAdapt <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-5/et_month_HadGEM2-CC_rcp45_2006-01.v0.CA_NV.tif"))  


```

```{r}
CalAdapt_rain <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-5/rainfall_month_CCSM4_rcp45_2006-01.v0.CA_NV.tif"))
 
```


```{r}
caladapt_calbers <- terra::project(CalAdapt, ca_raster)

#mask to CA
caladapt_masked <- mask(caladapt_calbers, ca_raster)

#test plot
plot(caladapt_masked)
```

```{r}
caladapt_rain_calbers <- terra::project(CalAdapt_rain, ca_raster)

#mask to CA
caladapt_rain_masked <- mask(caladapt_rain_calbers, ca_raster)

#test plot
plot(caladapt_rain_masked)
```
```{r}
#merging/stacking the rasters 
caladpat_merged <- c(caladapt_masked,caladapt_rain_masked)

#converting to a dataframe
caladpat_merged_df <- as.data.frame(caladpat_merged, xy=TRUE) %>% 
  rename(P = "rainfall_month_CCSM4_rcp45_2006-01.v0.CA_NV",
    PE = "et_month_HadGEM2-CC_rcp45_2006-01.v0.CA_NV")


# trying to figure out how to add PDSI calculation into DF
pdsi_df<-(pdsi(P,PE))

cal_adpat_pdsi_df <- dplyr::mutate(caladpat_merged_df,
                            pdsi_measure = (pdsi(P, PE)))

```

