---
title: "present_high_vs2030"
author: "Claire Meuter"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(terra)
library(sf)
#claire's file path
gdrive_data <- "/Users/clairemeuter/Library/CloudStorage/GoogleDrive-clairemeuter@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"
```

The purpose of this rmd is to compare  the area of high conflict risk zones under present day conditions to climate conditions in 2030 

```{r}
# read in the high conflict rasters 
hi_con_now <- rast(here(gdrive_data, "/AnalysisData/model_outputs/mod3sq_current_highconf.tif"))

hi_con_2030 <- rast(here(gdrive_data, "/AnalysisData/model_outputs/mod3sq_projected_highconf.tif"))
```

Find the area of hi_con_now 
```{r}
area_hi_con_now <- as.data.frame(hi_con_now) %>% 
  tally() %>% 
  mutate(area = (n * (res(hi_con_now)[1]))/ 1000000) * (res(hi_con_now)[2]))/ 1000000) #%>% 
  #covert to km^3
  #mutate(area_km = area / 1000000)
  
area_hi_con_now$area

#[1] 54,955,379
#54.95538 km
area_hi_con_2030 <- as.data.frame(hi_con_2030) %>% 
  tally() %>% 
  mutate(area = (n * res(hi_con_2030)[1] * res(hi_con_2030)[2])) 

# 231,363,204
```

