---
title: "dryad_readme"
author: "Claire Meuter"
date: "2023-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This README.md file was generated on 2023-05-15 by Claire Meuter


**GENERAL INFORMATION**
Metadata for 2023 MESM Group Project


Title of Dataset: Black Bear Aware: Predicting Human-Black Bear Conflict Likelihood in a Changing Climate


Author Information:
Claire Meuter: Data Manager
University of California, Santa Barbara
clairemeuter@bren.ucsb.edu


Mia Guarnieri: Project Manager 
University of California, Santa Barbara
mguarnieri@bren.ucsb.edu


Samantha Rozal: Finance Manager and Outreach Coordinator
University of California, Santa Barbara
srozal@bren.ucsb.edu 


Chase Tarr: Communications Manager
University of California, Santa Barbara
chasetarr@ucsb.edu




Date of data collection: 2022-05-01 to 2023-05-15




Geographic location of data collection: United States (USA) - California 


Information about funding sources that supported the collection of the data:
The project was generously funded by the Dipaola foundation.


**SHARING/ACCESS INFORMATION**


1\. Licenses/restrictions placed on the data: No licenses/restrictions are associated with this dataset.


2\. Recommended citation for this dataset:


Meuter, Claire; Guarnieri, Mia; Rozal, Samantha; Tarr, Chase (2023), Black Bear Aware: Predicting Human-Black Bear Conflict Likelihood in a Changing Climate; University of California Santa Barbara; 2022-2023., Dryad, Dataset, doi link here 


3\. Links/relationships to ancillary data sets:
Project github: https://github.com/miaguarnieri/black_bear_aware/tree/main


4\. Was data derived from another source? yes/no A. If yes, list
source(s):


Multiple datasets derived from same source:
Human Population Density Files Sourced from: https://landscan.ornl.gov/
* Raster files (tiff) of human population density for years 2016 - 2021
Land Cover Files Sourced from: https://www.mrlc.gov/data/nlcd-land-cover-conus-all-years
* Spatially explicit and reliable information on the land cover within the United States for years 2001, 2004, 2006, 2008, 2011, 2013, and 2016
Tree Canopy Cover - NLCD (Forest Density) files sourced from: “NLCD 2011 USFS Tree Canopy Cover (CONUS).” NLCD 2011 USFS Tree Canopy Cover (CONUS) | Multi-Resolution Land Characteristics (MRLC) Consortium, http://www.mrlc.gov/data/nlcd-2011-usfs-tree-canopy-cover-conus.  
* Displays the proportion of the land surface covered by trees for the years 2011 and 2016 from the National Land Cover Database (NLCD)
Digital Elevation Model (nor-cal & so-cal) files sourced from: https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-multi-resolution-terrain-elevation?qt-science_center_objects=0#qt-science_center_objects
* Set of 7 digital elevation model (DEM) rasters covering Northern and Southern California depicting minimum elevation, maximum elevation, mean elevation, median elevation, standard deviation of elevation, systematic subsample, and breakline emphasis. 
Projected Drought Files (Evapotranspiration & Precipitation) sourced from: https://cal-adapt.org/data/download/
* Set of Projected Evapotranspiration and Precipitation Values within the year 2030 based on a moderate emissions scenario (RCP 4.5)
US Drought Monitor (historical drought 2016-2021) files sourced from: https://droughtmonitor.unl.edu/DmData/DataDownload.aspx
* Palmer Drought Severity Index derived mean values for years 2016-2021 indicating severity of drought based on Palmer drought severity index equation. 
Recreational_areas: Folder contains shapefiles showing current Park Boundaries, Recreational Routes, Buildings, Structures, Day Use Areas (picnic grounds), Camping Areas, Parking Areas, and Park Entry Points throughout the state of California. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 








Individually Sourced Data:
*01_31-23_AnnualFireProjections_Isaac: Rasters included projections under RCP 4.5 and RCP 8.5 for annual fire projections developed in 2023. Sourced from: data currently not available for public viewing.
*2015_roads_TIGER: Shapefile shows roads within the state of California as of 2015. File sourced from https://www.census.gov/cgi-bin/geo/shapefiles/index.php. 
*2016_CAshp_Tiger: Shapefile of California for the year 2016. Used for reference spatial extent and resolution / california boundary. Sourced from: “CA Geographic Boundaries - CA State Boundary.” California Open Data, https://data.ca.gov/dataset/ca-geographic-boundaries/resource/3db1e426-fb51-44f5-82d5-a54d7c6e188b. 
*2017_Streams_CDFW: Data shows the streams throughout California as of 2017. Stream data was used to create distance to stream values for reported conflict. Sourced from: “California Streams.” California State Geoportal, https://gis.data.ca.gov/datasets/CDFW::california-streams/about. 
*2020_Fsim_FSRDA: Modeled burn probability and conditional flame-length probability for the United States (US) at a 270-meter grid spatial resolution for the year 2020. Used for future fire data in the model. Sourced from: Short, Karen C. et. al., 2020. Spatial datasets of probabilistic wildfire risk components for the United States (270m). 2nd Edition. Fort Collins, CO: Forest Service Research Data Archive. https://doi.org/10.2737/RDS-2016-0034-2.
*2021_FirePerimeters_Frap.gdb: Fire perimeters through 2021 for the state of California. Sourced from: “Fire and Resource Assessment Program.” Cal FIRE, https://www.fire.ca.gov/what-we-do/fire-resource-assessment-program. 
*2021_Roads_ESRI_tiff: Displays roads, streets, highways, bike paths, walkways, and other linear features in CONUS from the 2021 U.S. Census Bureau’s TIGER line geodatabase. Sourced from: Arcgis.Com, http://www.arcgis.com/home/item.html?id=ef89ed40fe6d46b19301391bfb99ceca. 
*2022_CA_ownershipFrap.gdb: Layer shows California multi-source land ownership designed to show non-private land ownership in California for the year 2022. Sourced from https://gis-calema.opendata.arcgis.com/datasets/5d7d1f6146f149fe83a1942d305b80b0_0/explore?location=37.177918%2C-119.270300%2C5.41. 
*2022_TIGER_censustract: Census Tract shapefile for the year 2022. Used for data visualization in Arc Storymap necessary for developed outreach materials. Sourced from: https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2022.html#list-tab-79044234. 
*Ca_counties_cagov : Shapefile of the designated boundaries of counties in California. Source shapefile from California State Geoportal and was created by the California Department of Forestry and Fire Protection https://gis.data.ca.gov/datasets/CALFIRE-Forestry::california-county-boundaries/about. 
*Ca_wui_block_1990_2020_change_shp: Layer is a shapefile of the wildland urban interface for the year 2020. Source shapefile from the US Department of Agriculture https://doi.org/10.2737/RDS-2015-0012-3.  
*Calenviroscreen40resultsdatadictionaryf2021: Used in demographic analysis to understand demographic patterns throughout the state of California for the year 2021. Sourced from “CalEnviroScreen.” Oehha.ca.Gov, https://oehha.ca.gov/calenviroscreen/maps-data/download-data.  
*Calenviroscreen40shpf2021shp: Used in demographic analysis to understand demographic patterns throughout the state of California for the year 2021. Sourced from: “CalEnviroScreen.” Oehha.ca.Gov, https://oehha.ca.gov/calenviroscreen/maps-data/download-data.
*cali_MSA_cagov: Shapefile layer of the boundaries of Metropolitan Statistical Areas in California. Source shapefile from State of California Employment Development Department with data provided by the US Census Bureau https://data.edd.ca.gov/Shapefiles/California-Metropolitan-Statistical-Areas-MSA-and-/sb8f-wnqx 
*CDFW_Regions: Regions of administration within the California Department of Fish and Wildlife. Sourced from: https://gis.data.ca.gov/datasets/CDFW::cdfw-regions/about. 
Demographics_data_2020: High resolution gridded estimates of sociodemographic demographics in california.  Data was forked from a github repository by njdepsky.(https://github.com/njdepsky/CA-POP ) which drew upon data from the 2020 census. This paper by Depsky et al. detailing the demographics data can be found here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0270746   
*fire_intensity_CA_mtbs: Thematic raster image of MTBS burn severity classes for all inventoried fires occurring in California during calendar year 2020. Fires omitted from this mapped inventory are those where suitable satellite imagery was not available or fires were not discernible from available imagery. Sourced from:“Burned Areas Boundaries Dataset.” MTBS, http://www.mtbs.gov/direct-download. 
*Geoportal_ca_counties: Folder contains shapefile of California County Boundaries. Sourced from: “California Counties.” California State Geoportal, https://gis.data.ca.gov/datasets/CALFIRE-Forestry::california-counties-1/explore?location=37.177658%2C-119.270300%2C6.41.
*NHD_H_California_State_GPKG: Layer shows a comprehensive set of digital spatial data that encodes information about naturally occurring and constructed bodies of water, paths through which waters flow, and related entities such as point features. File sourced from: https://data.cnra.ca.gov/dataset/national-hydrography-dataset-nhd. 
*rcp4.5_AnnualFireProjections_Isaac: Rasters included projections under RCP 4.5 and RCP 8.5 for annual fire projections within the state of California. Sourced from: Isaac Park from his 2021 publication: Data currently not available to the public. 
*SVI: SVI indicates the relative vulnerability of every U.S. Census tract. Census tracts are subdivisions of counties for which the Census collects statistical data. SVI ranks the tracts on 16 social factors, including unemployment, racial and ethnic minority status, and disability, and further groups them into four related themes. Thus, each tract receives a ranking for each Census variable and for each of the four themes as well as an overall ranking. Sourced from: https://sedac.ciesin.columbia.edu/data/set/usgrid-us-social-vulnerability-index/data-download. 






**DATA & FILE OVERVIEW**


1\. File List: 
Data is organized into three folders: InputData, IntermediateData, and AnalysisData. 
InputData holds unedited files downloaded from a variety of sources. IntermediateData holds data created prior to our final analysis that is required to complete the final analysis. Analysis data holds the final results of our analysis. 




**DATA-SPECIFIC INFORMATION FOR:** 


1. InputData
   1. 01_31-23_AnnualFireProjections_Isaac: Rasters included projections under RCP 4.5 and RCP 8.5 for annual fire projections developed in 2023. Sourced from: data currently not available for public viewing.
   2. 2010_DEM_USGSEROS_Norcal: Set of 7 digital elevation model (DEM) rasters covering Northern California depicting minimum elevation, maximum elevation, mean elevation, median elevation, standard deviation of elevation, systematic subsample, and breakline emphasis for the year 2010. File sourced from: “USGS Eros Archive - Digital Elevation - Global Multi-Resolution Terrain Elevation Data 2010 (GMTED2010) Active.” USGS EROS Archive - Digital Elevation - Global Multi-Resolution Terrain Elevation Data 2010 (GMTED2010) | U.S. Geological Survey, http://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-multi-resolution-terrain-elevation?qt-science_center_objects=0#qt-science_center_objects. 
   3. 2010_DEM_USGSEROS_Socal: Set of 7 digital elevation model (DEM) rasters covering Southern California depicting minimum elevation, maximum elevation, mean elevation, median elevation, standard deviation of elevation, systematic subsample, and breakline emphasis for the year 2010. File sourced from: “USGS Eros Archive - Digital Elevation - Global Multi-Resolution Terrain Elevation Data 2010 (GMTED2010) Active.” USGS EROS Archive - Digital Elevation - Global Multi-Resolution Terrain Elevation Data 2010 (GMTED2010) | U.S. Geological Survey, http://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-multi-resolution-terrain-elevation?qt-science_center_objects=0#qt-science_center_objects. 
   4. 2015_roads_TIGER: Shapefile shows roads within the state of California as of 2015. File sourced from https://www.census.gov/cgi-bin/geo/shapefiles/index.php. 
   5. 2016_CAshp_Tiger: Shapefile of California for the year 2016. Used for reference spatial extent and resolution / california boundary. Sourced from: “CA Geographic Boundaries - CA State Boundary.” California Open Data, https://data.ca.gov/dataset/ca-geographic-boundaries/resource/3db1e426-fb51-44f5-82d5-a54d7c6e188b. 
   6. 2017_Streams_CDFW: Data shows the streams throughout California as of 2017. Stream data was used to create distance to stream values for reported conflict. Sourced from: “California Streams.” California State Geoportal, https://gis.data.ca.gov/datasets/CDFW::california-streams/about. 
   7. 2020_Fsim_FSRDA: Modeled burn probability and conditional flame-length probability for the United States (US) at a 270-meter grid spatial resolution for the year 2020. Used for future fire data in the model. Sourced from: Short, Karen C., et al. “Spatial Datasets of Probabilistic Wildfire Risk Components for the United States (270m) (2nd Edition).” Home, http://www.fs.usda.gov/rds/archive/Catalog/RDS-2016-0034-2. 
   8. 2021_FirePerimeters_Frap.gdb: Fire perimeters through 2021 for the state of California. Sourced from: “Fire and Resource Assessment Program.” Cal FIRE, https://www.fire.ca.gov/what-we-do/fire-resource-assessment-program. 
   9. 2021_Roads_ESRI_tiff: Displays roads, streets, highways, bike paths, walkways, and other linear features in CONUS from the 2021 U.S. Census Bureau’s TIGER line geodatabase. Sourced from: Arcgis.Com, http://www.arcgis.com/home/item.html?id=ef89ed40fe6d46b19301391bfb99ceca. 
   10. 2022_TIGER_censustract: Census Tract shapefile for the year 2022. Used for data visualization in Arc Storymap necessary for developed outreach materials. Sourced from: https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2022.html#list-tab-79044234. 
   11. Ca_counties_cagov : Shapefile of the designated boundaries of counties in California. Source shapefile from California State Geoportal and was created by the California Department of Forestry and Fire Protection https://gis.data.ca.gov/datasets/CALFIRE-Forestry::california-county-boundaries/about. 
   12. Ca_wui_block_1990_2020_change_shp: Layer is a shapefile of the wildland urban interface for the year 2020. Source shapefile from the US Department of Agriculture https://doi.org/10.2737/RDS-2015-0012-3.  
   13. Calenviroscreen40resultsdatadictionaryf2021: Used in demographic analysis to understand demographic patterns throughout the state of California for the year 2021. Sourced from “CalEnviroScreen.” Oehha.ca.Gov, https://oehha.ca.gov/calenviroscreen/maps-data/download-data.  
   14. Calenviroscreen40shpf2021shp: Used in demographic analysis to understand demographic patterns throughout the state of California for the year 2021. Sourced from: “CalEnviroScreen.” Oehha.ca.Gov, https://oehha.ca.gov/calenviroscreen/maps-data/download-data.
   15. cali_MSA_cagov: Shapefile layer of the boundaries of Metropolitan Statistical Areas in California. Source shapefile from State of California Employment Development Department with data provided by the US Census Bureau https://data.edd.ca.gov/Shapefiles/California-Metropolitan-Statistical-Areas-MSA-and-/sb8f-wnqx 
   16. CDFW_Regions: Regions of administration within california department of fish and wildlife. Sourced from: https://gis.data.ca.gov/datasets/CDFW::cdfw-regions/about. 
   17. Demographics_data_2020: High resolution gridded estimates of sociodemographic demographics in california.  Data was forked from a github repository by njdepsky.(https://github.com/njdepsky/CA-POP ) which drew upon data from the 2020 census. This paper by Depsky et al. detailing the demographics data can be found here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0270746   
   18. Drought
      1. CalAdapt: sourced from: Scripps Institution of Oceanography. “Loca Vic Runs.” CalAdapt, https://cal-adapt.org/data/download/. Set of Projected Evapotranspiration and Precipitation Values within the year 2030 based on a moderate emissions scenario (RCP 4.5)
         1. et_month_HadGEM2-CC_rcp45_2030-01.v0.CA_NV.tif: Evapotranspiration Data for year 2030
         2. rainfall_month_CCSM4_rcp45_2030-01.v0.CA_NV.tif: Precipitation Data for year 2030
      2. Us_drought_monitor: sourced from: National Drought Mitigation Center (NDMC), U.S. Department of Agriculture (USDA), National Oceanic and Atmospheric Administration (NOAA). “Data Download.” Data Download | U.S. Drought Monitor, https://droughtmonitor.unl.edu/DmData/GISData.aspx. Palmer Drought Severity Index derived values for years 2016-2021 indicating severity of drought based on Palmer drought severity index equation. 
      3. USDM_shapefiles: sourced from National Drought Mitigation Center (NDMC), U.S. Department of Agriculture (USDA), National Oceanic and Atmospheric Administration (NOAA). “Data Download.” Data Download | U.S. Drought Monitor, https://droughtmonitor.unl.edu/DmData/GISData.aspx. Daily values of Palmer Drought Severity Index Values for years 2016-2021 in order to find mean of annual PDSI values.
   19. fire_intensity_CA_mtbs: Thematic raster image of MTBS burn severity classes for all inventoried fires occurring in California during calendar year 2020. Fires omitted from this mapped inventory are those where suitable satellite imagery was not available or fires were not discernible from available imagery. Sourced from:“Burned Areas Boundaries Dataset.” MTBS, http://www.mtbs.gov/direct-download. 
   20. Geoportal_ca_counties: Folder contains shapefile of California County Boundaries. Sourced from: “California Counties.” California State Geoportal, https://gis.data.ca.gov/datasets/CALFIRE-Forestry::california-counties-1/explore?location=37.177658%2C-119.270300%2C6.41.
   21. HumanPopulationDensity_LandScan: Raster files (tiff) of human population density for years 2016 - 2021. Source layers collected from: “Ornl LandScan Viewer - Oak Ridge National Laboratory.” ORNL LandScan Viewer - Oak Ridge National Laboratory, landscan.ornl.gov/. 
   22. LandCover_NLCD : National Land Cover Database, U.S. 
Geological Survey. “NLCD Land Cover (CONUS) All Years.” NLCD Land Cover (CONUS) All Years | Multi-Resolution Land Characteristics (MRLC) Consortium, http://www.mrlc.gov/data/nlcd-land-cover-conus-all-years. Spatially explicit and reliable information on the land cover within the United States for years 2001, 2004, 2006, 2008, 2011, 2013, and 2016
   23. NHD_H_California_State_GPKG: Layer shows a comprehensive set of digital spatial data that encodes information about naturally occurring and constructed bodies of water, paths through which waters flow, and related entities such as point features. File sourced from: https://data.cnra.ca.gov/dataset/national-hydrography-dataset-nhd. 
   24. rcp4.5_AnnualFireProjections_Isaac: Rasters included projections under RCP 4.5 and RCP 8.5 for annual fire projections within the state of California. Sourced from: Isaac Park from his 2021 publication: Data currently not available to the public. 
   25. Recreational_areas: Folder contains shapefiles showing current Park Boundaries, Recreational Routes, Buildings, Structures, Day Use Areas (picnic grounds), Camping Areas, Parking Areas, and Park Entry Points throughout the state of California. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   1. Buildings: Representation of the location of State Parks buildings. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   2. Campgrounds: Representation of the location and attributes of campgrounds within the California State Park System. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   3. Parkboundaries: Representation of the location of State Parks boundaries. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   4. Parkentrypoints: Representation of the location of park entry points. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   5. Parkingpoints: Representation of the location of State Parks parking areas. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682.  
   6. Picnicgrounds: Representation of the location of Parks picnic grounds. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682.  
   7. Recreationalroutes: Representation of the locations of Parks recreational routes. Sourced from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   8. Structures: Representation of the location of State Parks structures. Source from: California State Parks, State of California. “California State Parks Gis Data.” CA State Parks, http://www.parks.ca.gov/?page_id=29682. 
   26. SVI: SVI indicates the relative vulnerability of every U.S. Census tract. Census tracts are subdivisions of counties for which the Census collects statistical data. SVI ranks the tracts on 16 social factors, including unemployment, racial and ethnic minority status, and disability, and further groups them into four related themes. Thus, each tract receives a ranking for each Census variable and for each of the four themes as well as an overall ranking. Sourced from: https://sedac.ciesin.columbia.edu/data/set/usgrid-us-social-vulnerability-index/data-download. 
   27. TreeCanopyCover_NLCD: Displays the proportion of the land surface covered by trees for the years 2011 and 2016 from the National Land Cover Database (NLCD). Files sourced from: “NLCD 2011 USFS Tree Canopy Cover (CONUS).” NLCD 2011 USFS Tree Canopy Cover (CONUS) | Multi-Resolution Land Characteristics (MRLC) Consortium, http://www.mrlc.gov/data/nlcd-2011-usfs-tree-canopy-cover-conus.  
   1. 2011_TreeCanopyCover_NLCD: 2011 proportion of land surface covered by trees
   2. 2016_TreeCanopyCover_NLCD: 2016 proportion of land surface covered by trees


   2. IntermediateData


   28.  CARaster_Tiger_Formatted: Source layer was shapefile collected from: https://data.ca.gov/dataset/ca-geographic-boundaries/resource/3db1e426-fb51-44f5-82d5-a54d7c6e188b. Shapefile was rasterized in ArcGIS Pro. CRS was set to NAD83(2011) EPSG:6414. Extent was set to the state of California as defined by source shapefile. Resolution was set at 230 meters by 230 meters. 
   29. conflict_formatted: Due to privacy concerns, conflict data not available to the general public. If available to share, this folder would hold conflict occurrences as recorded by the California Department of Fish and Wildlife in their Wildlife Incident Reporting System. 
   30. land_own: This folder contains a raster (land_own_mask) of ownership types across California. Source layer was a shapefile collected from FRAP database: https://gis-calema.opendata.arcgis.com/datasets/5d7d1f6146f149fe83a1942d305b80b0_0/explore?location=37.177918%2C-119.270300%2C5.41. Source shapefile was rasterized in ArcGIS Pro and reclassified in R to include private land types. Land_own_mask’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available in the group Github in the public_vs_private_high_conflict_areas.Rmd. 
   31.  Model_ready: This folder contains variable layers prepared for use in the final model. 
   1. aspect: This raster layer is aspect across California. Source layer was collected from https://www.worldclim.org/data/worldclim21.html. Aspect was calculated in R from elevation layer (see model_ready/elevation metadata for more), using terra package function “terrain”. Code for processing this layer is available on the group Github in the other_data_wrangling.Rmd. Raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  


   2. dist_fire: This folder contains distance rasters for distance to nearest medium or fire intensity fire across California for years 2011 to 2020. Source layer was collected from: https://www.mtbs.gov/direct-download. Source layer was reclassified to only include medium and fire intensity fires. Distance layers were created in ArcGIS Pro using the Euclidean Distance tool. Resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available on the group Github in the fire_wrangling.Rmd.


   3. dist_forest: This folder contains distance rasters for distance to nearest forest across California for 2013, 2016, and 2019. Source layer was collected from https://www.mrlc.gov/data/nlcd-land-cover-conus-all-years. The source layer was a raster of land cover across California for 2013, 2016, and 2019. The source raster was reclassified to a binary raster with all other land cover types other than forests reclassified as NA. Distance rasters were created in ArcGIS Pro using the Euclidean Distance tool. Resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available on the group Github in the distance_rasters.Rmd. 


   4. dist_proj_fire: This folder contains distance rasters for distance to nearest projected fire across California for 2025 to 2026, 2027 to 2028, and 2029. Data was provided by Isaac Park from his 2021 publication: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0254723 Source rasters included projections under RCP 4.5 and RCP 8.5. Source layer was reclassified to only include projected fires of high probability. Distance rasters were created in ArcGIS Pro using the Euclidean Distance tool. Resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the fire_projection_wrangling.Rmd.

   5. dist_rec: This layer shows distance to recreational areas across California. This layer was created from park entry points, parking points, campgrounds, picnic grounds, structures, buildings, recreational routes, and park boundaries. See InputData for metadata on each source. Source layers were combined and rasterized to create a single raster of recreational areas across California. A distance raster was created in ArcGIS Pro using the Euclidean Distance tool. The resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the distance_rasters.Rmd.


      6. dist_road: This layer shows distance to the nearest road across California. Source layer was collected from https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.html. Source layer was rasterized in R. A distance raster was created in ArcGIS Pro using the Euclidean Distance tool. The resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the distance_rasters.Rmd.



         7. dist_stream: This layer shows distance to streams across California. Source layer was collected from https://gis.data.ca.gov/datasets/CDFW::california-streams/about. Source layers were rasterized in R. A distance raster was created in ArcGIS Pro using the Euclidean Distance tool. The resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the distance_rasters.Rmd.


         8. dist_urban: This folder contains raster layers for distance from urban areas across California for years 2013, 2016, and 2019. Source layer was collected from https://www.mrlc.gov/data/nlcd-land-cover-conus-all-years. The source layer was a raster of land cover across California for 2013, 2016, and 2019. The source raster was reclassified to a binary raster with all other land cover types other than urban areas reclassified as NA. Distance rasters were created in ArcGIS Pro using the Euclidean Distance tool. Resulting distance raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available on the group Github in the distance_rasters.Rmd. 


         9. drought_2016_2021: This folder contains rasters of average PDSI values by year for the state of California. Source layers were PDSI values across California by week from 2016 to 2021. https://droughtmonitor.unl.edu/DmData/GISData.aspx. Source layers were averaged to find the average PDSI value per year across California. The resulting raster layers’ extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available on the group Github in the drought_agg.Rmd. 


         10. drought_proj_2030: This folder contains a raster of projected PDSI across California for the year 2030. Source layers for this were projected Evapotranspiration and projected precipitation for the year 2030, sourced from the CalAdapt portal: https://cal-adapt.org/data/download/. Source layers were merged into one dataset, and PDSI values were created using the scPDSI package in R. The resulting raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the Drought_Projections.Rmd. 


         11. elevation: This file contains a tif of elevation across the state of California. Source layers were collected from USGS https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-global-multi-resolution-terrain-elevation?qt-science_center_objects=0#qt-science_center_objects. Source layers were merged to cover the entirety of California in R. The raster layers' extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the other_data_wrangling.Rmd. 


         12. land_cover: This file contains tifs of land cover across California by year (2013, 2016, and 2019). Source layers were collected from the NLCD at https://www.mrlc.gov/data/nlcd-land-cover-conus-all-years. Layer was reclassified in R from 16 land cover types to 12 more general land cover types. All of the raster layers' extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this data is available on the group Github in the nlcd_wrangling.Rmd. 
         13. Population_density: This folder contains population density rasters across California for years 2016 through 2021. Source layers were collected from https://landscan.ornl.gov/. All of the raster layers' extents, resolutions, and projections were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this data is available on the group Github in the human_pop_wrangling.Rmd.


         14. forest_density: Raster layer of forest density across California for 2016. Source layer was collected from https://www.mrlc.gov/data/nlcd-2011-usfs-tree-canopy-cover-conus. Raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  Code for processing this layer is available on the group Github in the forest_cover_wrangling.Rmd. 
         15. road_density: source layer was collected from https://www.arcgis.com/home/item.html?id=ef89ed40fe6d46b19301391bfb99ceca. Roads layer was processed in R and ArcGIS. Layer was reprojected, and crs was set in R. Road density was calculated in ArcGIS pro using the line density tool on 10/23/2022. After ArcGIS Pro processing, the raster layer’s extent, resolution, and projection were matched to the CARaster_Tiger_Formatted raster layer. Code for processing this layer is available on the group Github in the other_data_wrangling.Rmd


         16. terrain_ruggedness: Source layer was collected from https://www.worldclim.org/data/worldclim21.html. Terrain ruggedness was calculated in R from elevation layer (see model_ready/elevation metadata for more), using terra package function “terrain”. Code for processing this layer is available on the group Github in the other_data_wrangling.Rmd. Raster layer’s extent, resolution, and projection were processed in R to match the CARaster_Tiger_Formatted raster layer.  


         3. AnalysisData
         1. analysis_outputs: this folder contains several folders of additional analyses conducted on modeled current and projected conflict risk rasters. Code for creating these modeled raster outputs is available on the group Github in the data_vis.Rmd
         1. census_tract: Contains shapefiles of average conflict risk within each census tract for current and projected modeled conflict. Code for creating these shapefiles is available on the group Github in the zonal_stats_county.Rmd
         2. county_stats: Contains shapefiles showing area of high conflict within each california county for current and projected modeled conflict. Code for creating these shapefiles is available on the group Github in the high_conflict_area_calculations.Rmd
         3. high_conflict: Contains rasters and shapefiles of the area within the modeled current and projected conflict risk rasters that has a conflict risk greater than 0.7. These are binary files; any pixel or polygon with a conflict risk greater than 0.7 in the conflict risk raster has a value of 1 in these files, and all other pixels have a value of NA. Code for creating these files is available on the group Github in the high_conflict_area_calculations.Rmd
         2. model_dataframes: this folder contains two csv files of conflict and non-conflict points and their associated characteristics. Each row is a point within California. 
         1. Both files contain the following variables (columns)
         1. ID: 0 or 1, indicating conflict (1) or non-conflict (0)
         2. dem: elevation, in m
         3. aspect: aspect
         4. TRI: terrain ruggedness
         5. popdens: population density, people/10000m2
         6. lc: land cover, one of
         1. shrub_scrub
         2. barren_land
         3. grassland_herbaceous
         4. planted_cultivated
         5. forest 
         6. dev_high_int
         7. open_water
         8. dev_low_int
         9. dev_med_int
         10. dev_open_space          
         11. wetlands 
         12. perrenial_ice_snow
         7. road_dens: road density
         8. road_dist: distance to roads, in m
         9. streams_dist: distance to streams, in m
         10. urban_dist: distance to urban areas, in m
         11. rec_dist: distance to recreational areas, in m
         12. forest_dist: distance to forest, in m
         13. forest_dens: forest density
         14. year
         2. climate_model_data_allyears.csv additionally contains the following columns
         1. dist_fire_1yr: distance to fire in the preceding year, in m
         2. dist_fire_23yrs: distance to fire two to three years ago, in m
         3. dist_fire_45yrs: distance to fire four to five years ago, in m
         4. drought: annual mean Palmer Drought Severity Index in that location for the year the point was recorded
         3. model_outputs: This folder contains rasters of modeled current and projected (2030) conflict risk, as well as a raster of differenced conflict risk (modeled conflict risk in the year 2030 - modeled present day conflict risk). Code for creating these rasters is available on the group Github in the data_vis.Rmd








**METHODOLOGICAL INFORMATION**


Data was collected from a variety of open source data (see metadata for full list) and processed in ArcGIS Pro and R.