---
title: "WIR_data_cleaning"
author: "Claire Meuter"
date: "2022-07-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)

#mia and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

```

## WIR Data
Here I'll tidy up the WIR data, and remove accidental ' in coordinates 

## Read in the data 

```{r}

WIR_org <- read_csv(here(gdrive_data,"/InputData/InputData_Files/2022_07_05_WIRunedited_CDFW.csv"))

#the column names are not very clean, lets fix that first
```
```{r}
#code chunk to clean the column names 
WIR_clean <- WIR_org %>% clean_names()

# now all of the columns are in lower snake case, much better :)


```

```{r}
# Now we want to get rid of the unnecessary ' hanging before all my longitude points 

WIR_clean$longitude <- gsub("'","",as.character(WIR_clean$longitude))

# Cool, now that ' is taken out of our data, and we can start reading this data in Arc to map out the conflict occurrence points! 

#Now I want to remove a few erronous points. I have two that have bad lat long coordinates so we need to throw out WIR-2016-001081 row 4444  and WIR-2017-002420 row 4192 

WIR_clean_2 <- subset(WIR_clean,select longitude > 40 )

wir_clean_2 <-subset(WIR_clean,longitude < 40)


# Exporting.. 
write.csv(WIR_clean,"WIR_clean.csv", row.names = FALSE)

# This is just preliminary data to visualize our data, we'll likely want to tweak this data set going forward to make it better. A helpful addition would be a year column, so we can visualize the data by year in Arc. It might also be helpful to do months while we're at it. We also need to remove any erroneous points- let's get git working
```

