---
title: "zonal_stats_county"
author: "Sam Rozal"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach packages
library(tidyverse)
library(here)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)
library(rmapshaper)
library(terra)

#mia, chase, and claire's file path

#gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#mia's file path
#gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```


```{r}
#load in data
mod3_rast <- rast(here(gdrive_data, "/AnalysisData/model_outputs/projected_mod3_clim_map_squared.tif"))


ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

counties_shp_geoportal<- vect(here(gdrive_data,"/InputData/InputData_Files/geoportal_ca_counties/cnty19_1.shp"))

counties_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/ca_counties_2_28/ca_counties_new.tif"))

```

```{r}
#reformatt shapefile

counties_calber <- project(counties_raster, ca_raster)

counties_mask <- mask(counties_calber, ca_raster)

plot(counties_mask)

```
```{r}
counties_calber_shp <- project(counties_shp_geoportal, ca_raster)

counties_crop <- crop(counties_calber_shp, ca_raster)

plot(counties_crop)

```




```{r}
zonal_stat <- zonal(mod3_rast, counties_mask, fun="mean", na.rm=TRUE)
```

```{r}
zonal_statistic <-extract(mod3_rast, counties_crop, fun="mean", xy=TRUE, na.rm=TRUE)
```

