---
title: "Model Creation"
author: "Mia Guarnieri"
date: '2022-10-19'
output: html_document
---

##Setup and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach packages
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(lubridate)
library(ResourceSelection)
library(rmapshaper)

#mia, chase, and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"

```

#Load in data layers

```{r}
#conflict data
conflict_buffers <- read_sf(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/conflict_buffered_refined/conflict_buffered_refined.shp"))

conflict_points <- read_sf(here(gdrive_data, "/IntermediateData/IntermediateData_Files/conflict_formatted/conflict_points/conflict_points.shp"))

#elevation
dem <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/elevation/dem_formatted.tif"))

#aspect
aspect <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/aspect/aspect.tif"))

#terrain ruggedness
ter_rug <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/terrain_ruggedness/terrain_ruggedness.tif"))

#human pop density

pop16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2016_mask.tif"))

pop17 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2017_mask.tif"))

pop18 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2018_mask.tif"))

pop19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2019_mask.tif"))

pop20 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2020_mask.tif"))

pop21 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/population_density/pop_den_2021_mask.tif"))

#land cover

lc13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc13_reclassed.tif"))

lc16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc16_reclassed.tif"))

lc19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/land_cover/lc19_reclassed.tif"))

#road density

road_dens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/road_density/road_density_ca.tif"))

#distance to roads

road_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_road/model_ready/roads15_ca_distance.tif"))

#distance to streams

streams_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_stream/model_ready/stream17_ca_distance.tif"))

#distance to urban areas

urban_dist_13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua13_ca_distance.tif"))

urban_dist_16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua16_ca_distance.tif"))

urban_dist_19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_urban/model_ready/ua19_ca_distance.tif"))

#distance to recreational areas

rec_dist <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_rec/model_ready/rec_ca_distance.tif"))

#distance to forest cover

fc_dist_13 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc13_ca_distance.tif"))

fc_dist_16 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc16_ca_distance.tif"))

fc_dist_19 <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/distance_rasters/dist_to_forest/model_ready/fc19_ca_distance.tif"))

#forest density

fdens <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/model_ready/forest_density/forest_dens_2016_mask.tif"))

```

#Process data by year

##2016

```{r}

#extract values for 2016, select only conflict indicator and geometry, and dissolve polygons

con_16 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2016) %>% 
  select(conflict, geometry)

con_16_buff <- conflict_buffers %>% 
  filter(year == 2016) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra

conpoints_16_sv <- vect(con_16)

conbuff_16_sv <- vect(con_16_buff)

#read in the CA raster
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#make sure conflict is in the same projection
conpoints16_reproj <- project(conpoints_16_sv,crs(ca_raster))

conbuff16_reproj <- project(conbuff_16_sv,crs(ca_raster))

#convert back to sf for creation of inverse mask
conpoints16_sf <- st_as_sf(conpoints16_reproj)

conbuff16_sf <- st_as_sf(conbuff16_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out

conbuff16_inverse <- mask(ca_raster, conbuff16_reproj, inverse = TRUE)

tm_shape(conbuff16_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 
cabuff16_inv_pol <- as.polygons(conbuff16_inverse)

cabuff16_inv_sf <- st_as_sf(cabuff16_inv_pol)

#sampling random points from this misshapen california shpfile
#we sample 5X the amount of zeros for how many conflict points we have 
sample16 <- st_sample(cabuff16_inv_sf, 2135) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample16) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model

#sample16_buff <- st_buffer(sample16, dist = 5000) %>% 
#  st_as_sf()

#Testing to make sure the buffer worked
# tm_shape(sample16) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff16_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")

 
#removing non-conflict points that overlap
 
#intersect16 <- st_join(sample16, conbuff16_sf, join = st_intersects, left = FALSE)

#plot intersection
# 
# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons

zeros16 <- ms_erase(target = sample16, erase = conbuff16_sf)
 
 #plot to check that there is no overlap
 
 tm_shape(conbuff16_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros16) +
   tm_dots() +
  tmap_mode("view")

zeros16_formatted <- zeros16 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables

stack16 <- c(dem, aspect, ter_rug, pop16, lc16, road_dens, road_dist, streams_dist, urban_dist_16, rec_dist, fc_dist_16, fdens)

#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points

zero_vars16 <- extract(stack16, zeros16_formatted, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()


#union conflict points before extracting
#con_union16 <- con_16 %>% 
 # st_union() %>% 
 # vect()

con_vars16 <- extract(stack16, con_16, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()

#combine conflict and non-conflict

colnames(zero_vars16) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

colnames(con_vars16) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

model_df_16 <- rbind(zero_vars16, con_vars16)

#run it in the model

#model16 <- rspf(ID ~ dem + aspect + TRI + popdens1 + popdens2 + popdens3 + popdens4 + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = model_df_16)

#label the year for later binding with other dfs
modeldf_16_year <- model_df_16 %>% 
  mutate(year = 2016)

```

```{r}
#saving the files

write.csv(modeldf_16_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_16.csv"), row.names = FALSE)

#save the 2016 model output
#save(model16, file = here(gdrive_data, "/AnalysisData/models/10_31_2022/model_2016_noclimate/model_2016_noclimate.RData"))
```


##2017

```{r}
#extract values for 2017, select only conflict indictor and geometry, and dissolve polygons
con_17 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2017) %>% 
  select(conflict, geometry)

con_17_buff <- conflict_buffers %>% 
  filter(year == 2017) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra

conpoints_17_sv <- vect(con_17)
conbuff_17_sv <- vect(con_17_buff)

#read in the CA raster 
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#reproject the conflict data 
conpoints17_reproj <- project(conpoints_17_sv, crs(ca_raster))

conbuff17_reproj <- project(conbuff_17_sv, crs(ca_raster))

conpoints17_sf <- st_as_sf(conpoints17_reproj)
conbuff17_sf <- st_as_sf(conbuff17_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out
conbuff17_inverse <- mask(ca_raster, conbuff17_reproj, inverse = TRUE)
tm_shape(conbuff17_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 
cabuff17_inv_pol <- as.polygons(conbuff17_inverse)
cabuff17_inv_sf <- st_as_sf(cabuff17_inv_pol)

#sampling random points from this misshapen california shpfile
sample17 <- st_sample(cabuff17_inv_sf, 3345) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample17) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model
#sample17_buff <- st_buffer(sample17, dist = 5000) %>% 
#  st_as_sf()
#Testing to make sure the buffer worked
# tm_shape(sample17) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff17_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")

#removing non-conflict points that overlap
 
#intersect17 <- st_join(sample17, conbuff17_sf, join = st_intersects, left = FALSE)
#plot intersection
# 
# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons
zeros17 <- ms_erase(target = sample17, erase = conbuff17_sf)
 
 #plot to check that there is no overlap
 
tm_shape(conbuff17_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros17) +
   tm_dots() +
  tmap_mode("view")
 
zeros17_formatted <- zeros17 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables


stack17 <- c(dem, aspect, ter_rug, pop17, lc16, road_dens, road_dist, streams_dist, urban_dist_16,rec_dist,fc_dist_16, fdens)


#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points 
zero_vars17 <- extract(stack17, zeros17_formatted, method = "simple", bind = TRUE, ID = TRUE) %>% 
  as.data.frame()

#union conflict points before extracting 
#con_union17 <- con_17 %>% 
  #st_union() %>% 
  #vect()

con_vars17 <- extract(stack17, con_17, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()

#combine conflict and non-conflict
colnames(zero_vars17) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

colnames(con_vars17) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

model_df_17 <- rbind(zero_vars17, con_vars17)

#run it in the model
#model17 <- rspf(ID ~ dem + aspect + TRI + popdens1 + popdens2 + popdens3 + popdens4 + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = model_df_16)

#label the year for later binding with other dfs
modeldf_17_year <- model_df_17 %>% 
  mutate(year = 2017) 

```

```{r}
#save the file

write.csv(modeldf_17_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_17.csv"), row.names = FALSE)

```

##2018
```{r}
#extract values for 2018, select only conflict indicator and geometry, and dissolve polygons

con_18 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2018) %>% 
  select(conflict, geometry)

con_18_buff <- conflict_buffers %>% 
  filter(year == 2018) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra

conpoints_18_sv <- vect(con_18)

conbuff_18_sv <- vect(con_18_buff)

#read in the CA raster
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#make sure conflict is in the same projection
conpoints18_reproj <- project(conpoints_18_sv,crs(ca_raster))

conbuff18_reproj <- project(conbuff_18_sv,crs(ca_raster))

conpoints18_sf <- st_as_sf(conpoints18_reproj)

conbuff18_sf <- st_as_sf(conbuff18_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out

conbuff18_inverse <- mask(ca_raster, conbuff18_reproj, inverse = TRUE)

tm_shape(conbuff18_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 
cabuff18_inv_pol <- as.polygons(conbuff18_inverse)

cabuff18_inv_sf <- st_as_sf(cabuff18_inv_pol)


#sampling random points from this misshapen california shpfile
sample18 <- st_sample(cabuff18_inv_sf, 3635) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample18) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model

#sample18_buff <- st_buffer(sample18, dist = 5000) %>% 
#  st_as_sf()

#Testing to make sure the buffer worked
# tm_shape(sample18) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff18_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")

 
#removing non-conflict points that overlap
 
#intersect18 <- st_join(sample18, conbuff18_sf, join = st_intersects, left = FALSE)

#plot intersection
# 
# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons

zeros18 <- ms_erase(target = sample18, erase = conbuff18_sf)
 
 #plot to check that there is no overlap
 
 tm_shape(conbuff18_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros18) +
   tm_dots() +
  tmap_mode("view")

zeros18_formatted <- zeros18 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables

stack18 <- c(dem, aspect, ter_rug, pop18, lc16, road_dens, road_dist, streams_dist, urban_dist_16, rec_dist, fc_dist_16, fdens)

#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points
zero_vars18 <- extract(stack18, zeros18_formatted, method = "simple", bind = TRUE, ID = TRUE) %>% 
  as.data.frame()

#union conflict points before extracting
#con_union18 <- con_18 %>% 
  #st_union() %>% 
  #vect()

con_vars18 <- extract(stack18, con_18, method = "simple", bind = TRUE, ID = TRUE)%>%
  as.data.frame()

#combine conflict and non-conflict

colnames(zero_vars18) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

colnames(con_vars18) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

model_df_18 <- rbind(zero_vars18, con_vars18)

#run it in the model

#model18 <- rspf(ID ~ dem + aspect + TRI + popdens1 + popdens2 + popdens3 + popdens4 + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = model_df_18)

#label the year for later binding with other dfs
modeldf_18_year <- model_df_18 %>% 
  mutate(year = 2018)
```

```{r}
#save the file

#save(modeldf_18_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_1_2022/modeldf_18.csv"))

#EDIT: that save didn't work, trying this workaround

write.csv(modeldf_18_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_18.csv"), row.names = FALSE)
```

##2019

```{r}
#extract values for 2016, select only conflict indicator and geometry, and dissolve polygons
con_19 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2019) %>% 
  select(conflict, geometry)

con_19_buff <- conflict_buffers %>% 
  filter(year == 2019) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra

conpoints_19_sv <- vect(con_19)

conbuff_19_sv <- vect(con_19_buff)

#read in the CA raster
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#make sure conflict is in the same projection
conpoints19_reproj <- project(conpoints_19_sv,crs(ca_raster))

conbuff19_reproj <- project(conbuff_19_sv,crs(ca_raster))

conpoints19_sf <- st_as_sf(conpoints19_reproj)

conbuff19_sf <- st_as_sf(conbuff19_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out

conbuff19_inverse <- mask(ca_raster, conbuff19_reproj, inverse = TRUE)

tm_shape(conbuff19_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 
cabuff19_inv_pol <- as.polygons(conbuff19_inverse)

cabuff19_inv_sf <- st_as_sf(cabuff19_inv_pol)

#sampling random points from this misshapen california shpfile
sample19 <- st_sample(cabuff19_inv_sf, 3045) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample19) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model

#sample19_buff <- st_buffer(sample19, dist = 5000) %>% 
#  st_as_sf()

#Testing to make sure the buffer worked
# tm_shape(sample19) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff19_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")

 
#removing non-conflict points that overlap
 
#intersect16 <- st_join(sample19, conbuff19_sf, join = st_intersects, left = FALSE)

#plot intersection

# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons

zeros19 <- ms_erase(target = sample19, erase = conbuff19_sf)
 
 #plot to check that there is no overlap
 
 tm_shape(conbuff19_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros19) +
   tm_dots() +
  tmap_mode("view")

zeros19_formatted <- zeros19 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables

stack19 <- c(dem, aspect, ter_rug, pop19, lc19, road_dens, road_dist, streams_dist, urban_dist_19, rec_dist, fc_dist_19, fdens)

#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points
zero_vars19 <- extract(stack19, zeros19_formatted, method = "simple", bind = TRUE, ID = TRUE) %>% 
  as.data.frame()

#union conflict points before extracting- likely not using this anymore as of 11/12/2021
#con_union19 <- con_19 %>% 
  #st_union() %>% 
  #vect()

con_vars19 <- extract(stack19, con_19, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()

#combine conflict and non-conflict

colnames(zero_vars19) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

colnames(con_vars19) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

model_df_19 <- rbind(zero_vars19, con_vars19)

#label the year for later binding with other dfs
modeldf_19_year <- model_df_19 %>% 
  mutate(year = 2019)
```

```{r}
#save the file

write.csv(modeldf_19_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_19.csv"), row.names = FALSE)

```


##2020
```{r}

#extract values for 2020, select only conflict indicator and geometry, and dissolve polygons
con_20 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2020) %>% 
  select(conflict, geometry)

con_20_buff <- conflict_buffers %>% 
  filter(year == 2020) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra
conpoints_20_sv <- vect(con_20)
conbuff_20_sv <- vect(con_20_buff)

#read in the CA raster
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#make sure conflict is in the same projection

conpoints20_reproj <- project(conpoints_20_sv,crs(ca_raster))

conbuff20_reproj <- project(conbuff_20_sv,crs(ca_raster))

conpoints20_sf <- st_as_sf(conpoints20_reproj)

conbuff20_sf <- st_as_sf(conbuff20_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out

conbuff20_inverse <- mask(ca_raster, conbuff20_reproj, inverse = TRUE)

tm_shape(conbuff20_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 

cabuff20_inv_pol <- as.polygons(conbuff20_inverse)

cabuff20_inv_sf <- st_as_sf(cabuff20_inv_pol)

#sampling random points from this misshapen california shpfile

sample20 <- st_sample(cabuff20_inv_sf, 3995) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample20) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model
#sample16_buff <- st_buffer(sample16, dist = 5000) %>% 
#  st_as_sf()
#Testing to make sure the buffer worked
# tm_shape(sample16) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff16_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")
 
#removing non-conflict points that overlap
 
#intersect16 <- st_join(sample16, conbuff16_sf, join = st_intersects, left = FALSE)
#plot intersection
# 
# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons

zeros20 <- ms_erase(target = sample20, erase = conbuff20_sf)
 
 #plot to check that there is no overlap
 
 tm_shape(conbuff20_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros20) +
   tm_dots() +
  tmap_mode("view")
 

zeros20_formatted <- zeros20 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables

stack20 <- c(dem, aspect, ter_rug, pop20, lc19, road_dens, road_dist, streams_dist, urban_dist_19, rec_dist, fc_dist_19, fdens)

#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points
zero_vars20 <- extract(stack20, zeros20_formatted, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame() 

#union conflict points before extracting likely not using anymore 
#con_union20 <- con_20 %>% 
  #st_union() %>% 
 # vect()

con_vars20 <- extract(stack20, con_20, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()

#combine conflict and non-conflict

colnames(zero_vars20) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")


colnames(con_vars20) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")


model_df_20 <- rbind(zero_vars20, con_vars20)



#run it in the model
#model20 <- rspf(ID ~ dem + aspect + TRI + popdens1 + popdens2 + popdens3 + popdens4 + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = model_df_20)

#label the year for later binding with other dfs
modeldf_20_year <- model_df_20 %>% 
  mutate(year = 2020)
```

```{r}
#save the file

write.csv(modeldf_20_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_20.csv"), row.names = FALSE)
```

##2021

```{r}
#extract values for 2016, select only conflict indicator and geometry, and dissolve polygons

con_21 <- conflict_points %>% 
  separate(incdnt_d, into = c("inc_date", "inc_time"), sep = " ") %>% 
  separate(inc_date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(year = as.character.Date(year),
         "type" = cnfrmd_,
         "county" = cnty_nm,
         "conflict" = 1) %>% 
  select(conflict, wir_id:year, type, county, geometry) %>% 
  filter(year == 2021) %>% 
  select(conflict, geometry)

con_21_buff <- conflict_buffers %>% 
  filter(year == 2021) %>% 
  select(conflict, geometry)

#create a spatvector for processing in terra

conpoints_21_sv <- vect(con_21)

conbuff_21_sv <- vect(con_21_buff)

#read in the CA raster
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

#make sure conflict is in the same projection
conpoints21_reproj <- project(conpoints_21_sv,crs(ca_raster))

conbuff21_reproj <- project(conbuff_21_sv,crs(ca_raster))

conpoints21_sf <- st_as_sf(conpoints21_reproj)

conbuff21_sf <- st_as_sf(conbuff21_reproj)

#create an inverse mask- Anything withing the conflict buffer shapefiles will be a 0 value. So we get a California raster with all the conflict buffer locations zeroed out

conbuff21_inverse <- mask(ca_raster, conbuff21_reproj, inverse = TRUE)

tm_shape(conbuff21_inverse) +
  tm_raster() +
  tmap_mode("view")

#making the inverse raster a shapefile 
cabuff21_inv_pol <- as.polygons(conbuff21_inverse)

cabuff21_inv_sf <- st_as_sf(cabuff21_inv_pol)

#sampling random points from this misshapen california shpfile
sample21 <- st_sample(cabuff21_inv_sf, 6820) %>% 
  st_as_sf()

#mappping to see what it looks like 
tm_shape(sample21) +
  tm_dots() +
  tmap_mode("view")

#buffer the sample points - getting rid of this part for the sake of the model

#sample16_buff <- st_buffer(sample16, dist = 5000) %>% 
#  st_as_sf()

#Testing to make sure the buffer worked
# tm_shape(sample16) +
#    tm_dots(col  = "blue") +
# tm_shape(con_buff16_sf)+
#    tm_polygons(col  = "red") +
#    tmap_mode("view")

 
#removing non-conflict points that overlap
 
#intersect16 <- st_join(sample16, conbuff16_sf, join = st_intersects, left = FALSE)

#plot intersection

# tm_shape(intersect) +
#   tm_polygons() +
#   tmap_mode("view")

#remove the intersecting polygons

zeros21 <- ms_erase(target = sample21, erase = conbuff21_sf)
 
 #plot to check that there is no overlap
 
 tm_shape(conbuff21_sf) +
   tm_polygons(col = "blue") +
  tm_shape(zeros21) +
   tm_dots() +
  tmap_mode("view")

zeros21_formatted <- zeros21 %>% 
  mutate(conflict = 0) %>% 
  select(conflict, geometry) %>% 
  vect()

#create a raster stack of all variables

stack21 <- c(dem, aspect, ter_rug, pop21, lc19, road_dens, road_dist, streams_dist, urban_dist_19, rec_dist, fc_dist_19, fdens)

#extract data points from these rasters and add them to the shapefile dataframe

#nonconflict points
zero_vars21 <- extract(stack21, zeros21_formatted, method = "simple", bind = TRUE, ID = TRUE) %>% 
  as.data.frame() 

#union conflict points before extracting
#con_union21 <- con_21 %>% 
 # st_union() %>% 
 # vect()

con_vars21 <- extract(stack21, con_21, method = "simple", bind = TRUE, ID = TRUE) %>%
  as.data.frame()

#combine conflict and non-conflict

colnames(zero_vars21) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

colnames(con_vars21) <- c("ID", "dem", "aspect", "TRI", "popdens", "lc", "road_dens", "road_dist", "streams_dist", "urban_dist", "rec_dist", "forest_dist", "forest_dens")

model_df_21 <- rbind(zero_vars21, con_vars21)

#label the year for later binding with other dfs
modeldf_21_year <- model_df_21 %>% 
  mutate(year = 2021)
```

```{r}
#saving the file


write.csv(modeldf_21_year, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_21.csv"), row.names = FALSE)
```


#Combine the yearly dataframes

```{r}
#read them in

df16 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_16.csv"))

df17 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_17.csv"))

df18 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_18.csv"))

df19 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_19.csv"))

df20 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_20.csv"))

df21 <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/modeldf_21.csv"))



model_data_allyears <- rbind(df16, df17, df18, df19, df20, df21)

```

```{r}
#save the all year data frame

write.csv(model_data_allyears, file = here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/model_data_allyears.csv"), row.names = FALSE)
```


#Run the base model for all years

```{r}
#read in the data
model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_noclimate/12_13_2022/model_data_allyears.csv"))
```


# load in rdata


```{r}
basemodel_allyears <- rspf(ID ~ dem + aspect + TRI + popdens + lc + road_dens + road_dist + streams_dist + urban_dist + rec_dist + forest_dist + forest_dens, family = "binomial", m = 0, B = 1000, data = model_data)
```


```{r}
#save the model - this one isn't working for some reason (says it cannot open the connection?)

save(basemodel_allyears, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/basemodel_allyears.rds"))

#save the model

save(basemodel_allyears, file = here("models", "basemodel_allyears.rds"))

```

#Set up 5 alternative models, with the same covariates as the Hagani et al models

```{r}

#Model 1: elevation + land cover + distance to forests + population density + distance to recreational areas+ road density + distance to urban areas
mod1 <- rspf(ID ~ dem + lc + forest_dist + popdens + rec_dist + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = model_data)

#Model 2: elevation + forest density + land cover + distance to forests + population density + distance to recreational areas + road density + distance to urban areas

mod2 <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens + rec_dist + road_dens + urban_dist, family = "binomial", m = 0, B = 1000, data = model_data)

#Model 3: elevation + land cover + distance to forests + population density + distance to recreational areas + distance to streams + terrain ruggedness + distance to urban areas

mod3 <- rspf(ID ~ dem + lc + forest_dist + popdens + rec_dist + streams_dist + TRI + urban_dist, family = "binomial", m = 0, B = 1000, data = model_data)

#Model 4: elevation + forest density + land cover + distance to forests + population density + distance to recreational areas + distance to streams + distance to urban areas

mod4 <- rspf(ID ~ dem + forest_dens + lc + forest_dist + popdens + rec_dist + streams_dist + urban_dist, family = "binomial", m = 0, B = 1000, data = model_data)

#Model 5: elevation + land cover + distance to forests + population density + distance to streams + terrain ruggedness + distance to urban areas

mod5 <- rspf(ID ~ dem + lc + forest_dist + popdens + streams_dist + TRI + urban_dist, family = "binomial", m = 0, B = 1000, data = model_data)



```
#save the 5 models 

```{r}
#mod1
save(mod1, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/mod1.rds"))

#save the model

save(mod1, file = here("models", "mod1.rds"))

#mod2
save(mod2, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/mod2.rds"))

#save the model

save(mod2, file = here("models", "mod2.rds"))

#mod3
save(mod3, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/mod3.rds"))

#save the model

save(mod3, file = here("models", "mod3.rds"))

#mod4

save(mod4, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/mod4.rds"))

#save the model

save(mod4, file = here("models", "mod4.rds"))

#mod5
save(mod5, file = here(gdrive_data, "/AnalysisData/models/12_13_2022/model_allyears_noclimate/mod5.rds"))

#save the model

save(mod5, file = here("models", "mod5.rds"))

```

```{r}
#comparing AIC scores
AIC(mod1)

AIC(mod2)

AIC(mod3)

AIC(mod4)

AIC(mod5)


AIC(basemodel_allyears)

```

