---
title: "Drought Data"
author: "Chase Tarr"
date: '2022-10-20'
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
#note - Loading all of the ones Jason used, I don't think we will need all of them 

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(beepr)
library(rgeos)
library(rmapshaper)
library(rgdal)
library(raster)
library(stars)
library(purrr)


#mia's file path
gdrive_data <- "//Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"
```

```{r}
ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
```

# Read in drought data

```{r}
drought2016 <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2016/USDM_20161227.shp")) %>% 
  select(DM, geometry)

```




```{r}
drought_2022 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2022/USDM_20221025.shp"))
  #template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, ca_raster, fun = 'first')
})

plot(drought_2022[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2022")
```

```{r}
head(drought_2022)

#merge the layers of the list
drought2022_merged <- terra::merge(drought_2022[[1]], drought_2022[[2]], drought_2022[[3]], drought_2022[[4]], drought_2022[[5]])

#convert to a spatraster object for use in terra
d2022_rast <- rast(drought2022_merged)

#reproject
drought_2022_calbers <- terra::project(d2022_rast, ca_raster)

#mask to CA
d2022_masked <- mask(drought_2022_calbers, ca_raster)

#test plot
plot(d2022_masked)

```
```{r}
drought_2016 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2016/USDM_20161227.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2016[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2016")
```

```{r}
drought2016_merged <- terra::merge(drought_2016[[1]], drought_2016[[2]], drought_2016[[3]], drought_2016[[4]], drought_2016[[5]])

#convert to a spatraster object for use in terra
d2016_rast <- rast(drought2016_merged)

#reproject
drought_2016_calbers <- terra::project(d2016_rast, ca_raster)

#mask to CA
d2016_masked <- mask(drought_2016_calbers, ca_raster)
```

```{r}
drought_2017 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2017/USDM_20170905.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2017[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2017")
```

```{r}
drought2017_merged <- terra::merge(drought_2017[[1]], drought_2017[[2]], drought_2017[[3]], drought_2017[[4]], drought_2017[[5]])

#convert to a spatraster object for use in terra
d2017_rast <- rast(drought2017_merged)

#reproject
drought_2017_calbers <- terra::project(d2017_rast, ca_raster)

#mask to CA
d2017_masked <- mask(drought_2017_calbers, ca_raster)
```

```{r}
drought_2018 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2018/USDM_20180904.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2018[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2022")
```

```{r}
drought2018_merged <- terra::merge(drought_2018[[1]], drought_2018[[2]], drought_2018[[3]], drought_2018[[4]], drought_2018[[5]])

#convert to a spatraster object for use in terra
d2018_rast <- rast(drought2018_merged)

#reproject
drought_2018_calbers <- terra::project(d2018_rast, ca_raster)

#mask to CA
d2018_masked <- mask(drought_2018_calbers, ca_raster)
```

```{r}
drought_2019 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2019/USDM_20190903.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2019[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2019")
```

```{r}
drought2019_merged <- terra::merge(drought_2019[[1]], drought_2019[[2]], drought_2019[[3]], drought_2019[[4]], drought_2019[[5]])

#convert to a spatraster object for use in terra
d2019_rast <- rast(drought2019_merged)

#reproject
drought_2019_calbers <- terra::project(d2019_rast, ca_raster)

#mask to CA
d2019_masked <- mask(drought_2019_calbers, ca_raster)
```

```{r}
drought_2020 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2020/USDM_20200908.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2020[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2020")
```

```{r}
drought2020_merged <- terra::merge(drought_2020[[1]], drought_2020[[2]], drought_2020[[3]], drought_2020[[4]], drought_2020[[5]])

#convert to a spatraster object for use in terra
d2020_rast <- rast(drought2020_merged)

#reproject
drought_2020_calbers <- terra::project(d2020_rast, ca_raster)

#mask to CA
d2020_masked <- mask(drought_2020_calbers, ca_raster)
```

```{r}
drought_2021 <- lapply(c("D0", "D1", "D2", "D3", "D4"), function(i){
  shp <- readOGR(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2021/USDM_20210907.shp"))
  template <- raster(ext = extent(shp), crs = projection(shp))
  rst <- rasterize(shp, template, fun = 'first')
})

plot(drought_2021[[2]], xlab = "lon", ylab = "lat", main = "Drought Index 2022")
```

```{r}
drought2021_merged <- terra::merge(drought_2021[[1]], drought_2021[[2]], drought_2021[[3]], drought_2021[[4]], drought_2021[[5]])

#convert to a spatraster object for use in terra
d2021_rast <- rast(drought2021_merged)

#reproject
drought_2021_calbers <- terra::project(d2021_rast, ca_raster)

#mask to CA
d2021_masked <- mask(drought_2021_calbers, ca_raster)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2022", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2022_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2026", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2016_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2017", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2017_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2018", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2018_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2019", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2019_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2020", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2020_masked)
```

```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/us_drought_monitor/2021", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2021_masked)
```


#looking into drought projections
```{r}
drought_2048 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2048.tif"))

tm_shape(drought_2048) +
  tm_raster() +
  tmap_mode("view")

#d2048_mask = resample(drought_2048, ca_raster)

d2048_project <- terra::project(drought_2048, ca_raster)

#crop to CA 
d2048 <- mask(d2048_project, ca_raster)

tm_shape(d2048) +
  tm_raster() +
  tmap_mode("view")
```

#reading in projected drought rasters
```{r}
drought_2006 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2006.tif"))
drought_2007 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2007.tif"))
drought_2008 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2008.tif"))
drought_2009 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2009.tif"))
drought_2010 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2010.tif"))
drought_2011 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2011.tif"))
drought_2012 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2012.tif"))
drought_2013 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2013.tif"))
drought_2014 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2014.tif"))
drought_2015 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2015.tif"))
drought_2016 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2016.tif"))
drought_2017 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2017.tif"))
drought_2018 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2018.tif"))
drought_2019 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2019.tif"))
drought_2020 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2020.tif"))
drought_2021 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2021.tif"))
drought_2022 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2022.tif"))
drought_2023 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2023.tif"))
drought_2024 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2024.tif"))
drought_2025 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2025.tif"))
drought_2026 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2026.tif"))
drought_2027 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2027.tif"))
drought_2028 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2028.tif"))
drought_2029 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2029.tif"))
drought_2030 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2030.tif"))
drought_2031 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2031.tif"))
drought_2032 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2032.tif"))
drought_2033 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2033.tif"))
drought_2034 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2034.tif"))
drought_2035 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2035.tif"))
drought_2036 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2036.tif"))
drought_2037 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2037.tif"))
drought_2038 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2038.tif"))
drought_2039 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2039.tif"))
drought_2040 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2040.tif"))
drought_2041 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2041.tif"))
drought_2042 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2042.tif"))
drought_2043 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2043.tif"))
drought_2044 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2044.tif"))
drought_2045 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2045.tif"))
drought_2046 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2046.tif"))
drought_2047 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2047.tif"))
drought_2048 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2048.tif"))
drought_2049 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2049.tif"))
drought_2050 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2050.tif"))
drought_2051 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2051.tif"))
drought_2052 <- rast(here(gdrive_data, "/InputData/InputData_Files/Drought/CalAdapt/data-2/tair_vic_models_max_rcp85-2052.tif"))

```

```{r}
reproj_mask <- function(x){
  
  x_reproj <- terra::project(x,ca_raster)
  
  x_mask <- mask(x_reproj, ca_raster)
  
  return(x_mask)
}
```

#formatting all drought files from CalAdapt
```{r}
d2006 <- reproj_mask(drought_2006)
d2007 <- reproj_mask(drought_2007)
d2008 <- reproj_mask(drought_2008)
d2009 <- reproj_mask(drought_2009)
d2010 <- reproj_mask(drought_2010)
d2011 <- reproj_mask(drought_2011)
d2012 <- reproj_mask(drought_2012)
d2013 <- reproj_mask(drought_2013)
d2014 <- reproj_mask(drought_2014)
d2015 <- reproj_mask(drought_2015)
d2016 <- reproj_mask(drought_2016)
d2017 <- reproj_mask(drought_2017)
d2018 <- reproj_mask(drought_2018)
d2019 <- reproj_mask(drought_2019)
d2020 <- reproj_mask(drought_2020)
d2021 <- reproj_mask(drought_2021)
d2022 <- reproj_mask(drought_2022)
d2023 <- reproj_mask(drought_2023)
d2024 <- reproj_mask(drought_2024)
d2025 <- reproj_mask(drought_2025)
d2026 <- reproj_mask(drought_2026)
d2027 <- reproj_mask(drought_2027)
d2028 <- reproj_mask(drought_2028)
d2029 <- reproj_mask(drought_2029)
d2030 <- reproj_mask(drought_2030)
d2031 <- reproj_mask(drought_2031)
d2032 <- reproj_mask(drought_2032)
d2033 <- reproj_mask(drought_2033)
d2034 <- reproj_mask(drought_2034)
d2035 <- reproj_mask(drought_2035)
d2036 <- reproj_mask(drought_2036)
d2037 <- reproj_mask(drought_2037)
d2038 <- reproj_mask(drought_2038)
d2039 <- reproj_mask(drought_2039)
d2040 <- reproj_mask(drought_2040)
d2041 <- reproj_mask(drought_2041)
d2042 <- reproj_mask(drought_2042)
d2043 <- reproj_mask(drought_2043)
d2044 <- reproj_mask(drought_2044)
d2045 <- reproj_mask(drought_2045)
d2046 <- reproj_mask(drought_2046)
d2047 <- reproj_mask(drought_2047)
d2048 <- reproj_mask(drought_2048)
d2049 <- reproj_mask(drought_2049)
d2050 <- reproj_mask(drought_2050)
d2051 <- reproj_mask(drought_2051)
d2052 <- reproj_mask(drought_2052)
```

#saving these projected rasters to model ready folder
```{r}
saverast <- function(x){
  
 name <- paste0(deparse(substitute(x)), ".tif") #the name of the file will be the same as the input object, plus '.tif' at the end
  
#write the raster into the correct folder in drive (the path will need to be updated for other files) and save it as a geotiff
  
writeRaster(x, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/caladapt_model_ready", name), filetype = "Gtiff", overwrite=TRUE)
}

saverast(d2006)
saverast(d2007)
saverast(d2008)
saverast(d2009)
saverast(d2010)
saverast(d2011)
saverast(d2012)
saverast(d2013)
saverast(d2014)
saverast(d2015)
saverast(d2016)
saverast(d2017)
saverast(d2018)
saverast(d2019)
saverast(d2020)
saverast(d2021)
saverast(d2022)
saverast(d2023)
saverast(d2024)
saverast(d2025)
saverast(d2026)
saverast(d2027) 
saverast(d2028)
saverast(d2029)
saverast(d2030)
saverast(d2031)
saverast(d2032)
saverast(d2033)
saverast(d2034)
saverast(d2035)
saverast(d2036)
saverast(d2037)
saverast(d2038)
saverast(d2039)
saverast(d2040)
saverast(d2041)
saverast(d2042)
saverast(d2043)
saverast(d2044)
saverast(d2045)
saverast(d2046)
saverast(d2047)
saverast(d2048)
saverast(d2049)
saverast(d2050)
saverast(d2051)
saverast(d2052)
```

