---
title: "Drought aggregation"
author: "Mia Guarnieri"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(rgdal)

#mia's file path
gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
#gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"
```

#Exploring single sf file to test

```{r}
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))

drought16 <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/us_drought_monitor/2016/USDM_20161227.shp")) 

#%>% 
 # select(DM)

d16vect <- vect(drought16) %>% 
 terra::project(., caraster)

d16rast <- rasterize(d16vect, caraster, field = "DM")

d16rast_ca <- mask(d16rast, caraster)

plot(d16rast_ca)

```


##2016

```{r}
#create a list of the shapefile names
d16_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2016_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d16_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2016_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2016", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d16_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2016"))

#stack up all raster files and take the mean
stack16 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2016/", d16_rast_list)))

mean_16 <- terra::mean(stack16, na.rm = TRUE)

#save the mean raster
writeRaster(mean_16, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2016/mean_drought_16.tif"), filetype = "GTiff", overwrite = TRUE)
  
```

##2017

```{r}

#create a list of the shapefile names
d17_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2017_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d17_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2017_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2017", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d17_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2017"))

#stack up all raster files and take the mean
stack17 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2017/", d17_rast_list)))

mean_17 <- terra::mean(stack17, na.rm = TRUE)

#save the mean raster
writeRaster(mean_17, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2017/mean_drought_17.tif"), filetype = "GTiff", overwrite = TRUE)

```

## 2018

```{r}

#create a list of the shapefile names
d18_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2018_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d18_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2018_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2018", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d18_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2018"))

#stack up all raster files and take the mean
stack18 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2018/", d18_rast_list)))

mean_18 <- terra::mean(stack18, na.rm = TRUE)

#save the mean raster
writeRaster(mean_18, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2018/mean_drought_18.tif"), filetype = "GTiff", overwrite = TRUE)
```

#2019

```{r}
#create a list of the shapefile names
d19_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2019_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d19_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2019_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2019", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d19_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2019"))

#stack up all raster files and take the mean
stack19 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2019/", d19_rast_list)))

mean_19 <- terra::mean(stack19, na.rm = TRUE)

#save the mean raster
writeRaster(mean_19, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2019/mean_drought_19.tif"), filetype = "GTiff", overwrite = TRUE)
```

# 2020

```{r}
#create a list of the shapefile names
d20_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2020_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d20_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2020_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2020", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d20_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2020"))

#stack up all raster files and take the mean
stack20 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2020/", d20_rast_list)))

mean_20 <- terra::mean(stack20, na.rm = TRUE)

#save the mean raster
writeRaster(mean_20, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2020/mean_drought_20.tif"), filetype = "GTiff", overwrite = TRUE)

```

# 2021

```{r}

#create a list of the shapefile names
d21_list <- list.files(path = here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2021_USDM_M"), pattern = '.shp')

#read each file in that list, convert it to a raster, and save it to intermediate data
for (i in d21_list) {
  
caraster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Formatted/formattedcaraster.tif"))
  
drought <- read_sf(here(gdrive_data, "/InputData/InputData_Files/Drought/USDM_shapefiles/2021_USDM_M", i))
  
drought_vect <- vect(drought) %>% 
  terra::project(., caraster)
  
drought_rast <- rasterize(drought_vect, caraster, field = "DM")
  
drought_rast_ca <- mask(drought_rast, caraster)
  
name <- paste0(i, ".tif") #the name of the file will be the same as the input file, plus '.tif' at the end
  
  writeRaster(drought_rast_ca, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2021", name), filetype = "GTiff", overwrite = TRUE)
  
}

#create a list of raster names
d21_rast_list <- list.files(path = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2021"))

#stack up all raster files and take the mean
stack21 <- c(rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2021/", d21_rast_list)))

mean_21 <- terra::mean(stack21, na.rm = TRUE)

#save the mean raster
writeRaster(mean_21, filename = here(gdrive_data, "/IntermediateData/IntermediateData_Files/drought/drought_rasters/UDM_2021/mean_drought_21.tif"), filetype = "GTiff", overwrite = TRUE)

```

