---
title: "Drought Projections"
author: "Mia Guarnieri"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)

gdrive_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/Shared drives/Black_Bear_Aware/gdrive_data"

```


#Test
```{r}
library(RNetCDF)
library(tidync)

test <- tidync(here(gdrive_data, "/InputData/InputData_Files/Drought/ncar_netcdf_pdsi/pdsisc.monthly.maps.1900-2099.r2.5x2.5.EnsAvg14Models.CMIP5.RCP4.5.TP2.ipe-2.nc"))

test

test_filter <- hyper_filter(test, 
                            time = time >= 2030 & time < 2030.9)

test_filter

ncdf4::ncvar_get(test_filter, "time")

time <- ncvar_get(test, "time") %>% 
  as.data.frame()

colnames(time) = "time"

timedf<- as.data.frame(as.character(time)) %>% 
  separate(.,
           into = c("year", "mo"),
           sep = ".",
           extra = "merge")

ncdf.rast <- rast(here("data", "PDSI.nc"))

```

