---
title: "collinearity_tests"
author: "Claire Meuter"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usdm)
library(corrplot)
library(tidyverse)
library(raster)
library(tmap)
library(here)
library(sf)
library(ResourceSelection)

#mia, chase, and claire's file path
#gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

#sam's file path
gdrive_data <- "G:/Shared drives/Black_Bear_Aware/gdrive_data"


```

#Summary:

This rmd contains the code to test for collinearity between the variables used in our model. Coorelation is tested in lines 33-62, other lines of code are extraneous


```{r}
#load in the the model
model<- load(here("models", "climate_model_allyears.rds")) #you have to name the object "model or it will not read in right


```


```{r}
#read in the data
climate_model_data <- read_csv(here(gdrive_data, "/AnalysisData/model_df_climate/11_10_2022/climate_model_data_allyears.csv"))

```

```{r}
#construct correlation matrix
data_model_matrix <- model.matrix(~0+., data=climate_model_data) 
cor_matrix <- cor(data_model_matrix)
corrplot(cor_matrix)

cor_matrix_2 <- cor(cor_matrix, method = c("pearson"))

corrplot(cor_matrix_2)
cor_matrix

```

```{r}
#construct correlation matrix with numbers
cor_matrix_num <- corrplot(cor_matrix, method="number")
```


#extra data wrangling 
```{r}
climate_model_data_numeric <- climate_model_data$lc[, c('shrub_scrub', 'grassland_herbaceous','barren_land', 'forest', 'dev_open_space', 'planted_cultivated', 'open_water', 'dev_low_int', 'dev_med_int', 'dev_high_int', 'wetlands', 'undefined', 'perrenial_ice_snow', 'NA' )] <- sapply(climate_model_data$lc[, c('shrub_scrub', 'grassland_herbaceous','barren_land', 'forest', 'dev_open_space', 'planted_cultivated', 'open_water', 'dev_low_int', 'dev_med_int', 'dev_high_int', 'wetlands', 'undefined', 'perrenial_ice_snow', 'NA' )], unclass)
```

```{r}
#unclass to organize
unclass(climate_model_data$lc[, c('shrub_scrub', 'grassland_herbaceous','barren_land', 'forest', 'dev_open_space', 'planted_cultivated', 'open_water', 'dev_low_int', 'dev_med_int', 'dev_high_int', 'wetlands', 'undefined', 'perrenial_ice_snow', 'NA' )]
```


```{r}
#create cor matrix
cor.matrix <- cor(climate_model_data, method = c("pearson"))

```

